/* _GlobalPrefix_ */
"use strict";this.default_host=this.default_host||{};(function(_){var window=this;
/* _Module_:ultraviolet_base_module */
try{
_.aa=_.aa||{};_.l=this;_.ba="closure_uid_"+(1E9*Math.random()>>>0);_.m=Date.now||function(){return+new Date};
}catch(e){_._DumpException(e)}
/* _Module_:sy0 */
try{
var la,ma;_.p=function(a){return void 0!==a};_.q=function(a){return"string"==typeof a};_.da=function(a){return"number"==typeof a};_.ea=function(a){a=a.split(".");for(var b=_.l,c=0;c<a.length;c++)if(b=b[a[c]],null==b)return null;return b};_.fa=function(){};
_.ha=function(a){var b=typeof a;if("object"==b)if(a){if(a instanceof Array)return"array";if(a instanceof Object)return b;var c=Object.prototype.toString.call(a);if("[object Window]"==c)return"object";if("[object Array]"==c||"number"==typeof a.length&&"undefined"!=typeof a.splice&&"undefined"!=typeof a.propertyIsEnumerable&&!a.propertyIsEnumerable("splice"))return"array";if("[object Function]"==c||"undefined"!=typeof a.call&&"undefined"!=typeof a.propertyIsEnumerable&&!a.propertyIsEnumerable("call"))return"function"}else return"null";
else if("function"==b&&"undefined"==typeof a.call)return"object";return b};_.t=function(a){return"array"==_.ha(a)};_.ia=function(a){var b=_.ha(a);return"array"==b||"object"==b&&"number"==typeof a.length};_.ja=function(a){return"function"==_.ha(a)};_.ka=function(a){var b=typeof a;return"object"==b&&null!=a||"function"==b};la=function(a,b,c){return a.call.apply(a.bind,arguments)};
ma=function(a,b,c){if(!a)throw Error();if(2<arguments.length){var d=Array.prototype.slice.call(arguments,2);return function(){var c=Array.prototype.slice.call(arguments);Array.prototype.unshift.apply(c,d);return a.apply(b,c)}}return function(){return a.apply(b,arguments)}};_.u=function(a,b,c){Function.prototype.bind&&-1!=Function.prototype.bind.toString().indexOf("native code")?_.u=la:_.u=ma;return _.u.apply(null,arguments)};
_.na=function(a,b){var c=Array.prototype.slice.call(arguments,1);return function(){var b=c.slice();b.push.apply(b,arguments);return a.apply(this,b)}};_.oa=function(a,b){a=a.split(".");var c=_.l;a[0]in c||!c.execScript||c.execScript("var "+a[0]);for(var d;a.length&&(d=a.shift());)!a.length&&_.p(b)?c[d]=b:c[d]&&c[d]!==Object.prototype[d]?c=c[d]:c=c[d]={}};
_.v=function(a,b){function c(){}c.prototype=b.prototype;a.A=b.prototype;a.prototype=new c;a.prototype.constructor=a;a.Xc=function(a,c,f){for(var d=Array(arguments.length-2),e=2;e<arguments.length;e++)d[e-2]=arguments[e];return b.prototype[c].apply(a,d)}};
_.pa=function(a){if(Error.captureStackTrace)Error.captureStackTrace(this,_.pa);else{var b=Error().stack;b&&(this.stack=b)}a&&(this.message=String(a))};_.v(_.pa,Error);_.pa.prototype.name="CustomError";var va,xa;_.qa=function(a,b){return 0==a.lastIndexOf(b,0)};_.ra=function(a,b){var c=a.length-b.length;return 0<=c&&a.indexOf(b,c)==c};_.sa=function(a){return/^[\s\xa0]*$/.test(a)};_.ua=String.prototype.trim?function(a){return a.trim()}:function(a){return a.replace(/^[\s\xa0]+|[\s\xa0]+$/g,"")};va=String.prototype.repeat?function(a,b){return a.repeat(b)}:function(a,b){return Array(b+1).join(a)};_.wa=function(a){return null==a?"":String(a)};
_.ya=function(a,b){var c=0;a=(0,_.ua)(String(a)).split(".");b=(0,_.ua)(String(b)).split(".");for(var d=Math.max(a.length,b.length),e=0;0==c&&e<d;e++){var f=a[e]||"",h=b[e]||"";do{f=/(\d*)(\D*)(.*)/.exec(f)||["","","",""];h=/(\d*)(\D*)(.*)/.exec(h)||["","","",""];if(0==f[0].length&&0==h[0].length)break;c=xa(0==f[1].length?0:(0,window.parseInt)(f[1],10),0==h[1].length?0:(0,window.parseInt)(h[1],10))||xa(0==f[2].length,0==h[2].length)||xa(f[2],h[2]);f=f[3];h=h[3]}while(0==c)}return c}; xa=function(a,b){return a<b?-1:a>b?1:0};
var za;za=Array.prototype.indexOf?function(a,b,c){return Array.prototype.indexOf.call(a,b,c)}:function(a,b,c){c=null==c?0:0>c?Math.max(0,a.length+c):c;if(_.q(a))return _.q(b)&&1==b.length?a.indexOf(b,c):-1;for(;c<a.length;c++)if(c in a&&a[c]===b)return c;return-1};_.x=Array.prototype.forEach?function(a,b,c){Array.prototype.forEach.call(a,b,c)}:function(a,b,c){for(var d=a.length,e=_.q(a)?a.split(""):a,f=0;f<d;f++)f in e&&b.call(c,e[f],f,a)};
_.Aa=Array.prototype.filter?function(a,b,c){return Array.prototype.filter.call(a,b,c)}:function(a,b,c){for(var d=a.length,e=[],f=0,h=_.q(a)?a.split(""):a,k=0;k<d;k++)if(k in h){var n=h[k];b.call(c,n,k,a)&&(e[f++]=n)}return e};_.Ba=Array.prototype.map?function(a,b,c){return Array.prototype.map.call(a,b,c)}:function(a,b,c){for(var d=a.length,e=Array(d),f=_.q(a)?a.split(""):a,h=0;h<d;h++)h in f&&(e[h]=b.call(c,f[h],h,a));return e};
_.Ca=Array.prototype.some?function(a,b,c){return Array.prototype.some.call(a,b,c)}:function(a,b,c){for(var d=a.length,e=_.q(a)?a.split(""):a,f=0;f<d;f++)if(f in e&&b.call(c,e[f],f,a))return!0;return!1};_.Ea=function(a,b){b=_.Da(a,b,void 0);return 0>b?null:_.q(a)?a.charAt(b):a[b]};_.Da=function(a,b,c){for(var d=a.length,e=_.q(a)?a.split(""):a,f=0;f<d;f++)if(f in e&&b.call(c,e[f],f,a))return f;return-1};_.Fa=function(a,b){return 0<=za(a,b)};_.Ha=function(a,b){b=za(a,b);var c;(c=0<=b)&&_.Ga(a,b);return c}; _.Ga=function(a,b){return 1==Array.prototype.splice.call(a,b,1).length};_.Ia=function(a){return Array.prototype.concat.apply([],arguments)};_.Ja=function(a){var b=a.length;if(0<b){for(var c=Array(b),d=0;d<b;d++)c[d]=a[d];return c}return[]};
a:{var La=_.l.navigator;if(La){var Ma=La.userAgent;if(Ma){_.Ka=Ma;break a}}_.Ka=""}_.y=function(a){return-1!=_.Ka.indexOf(a)};var Oa,Pa,Qa,Sa;_.Na=function(a,b,c){for(var d in a)b.call(c,a[d],d,a)};Oa=function(a,b){for(var c in a)if(b.call(void 0,a[c],c,a))return!0;return!1};Pa=function(a){var b=[],c=0,d;for(d in a)b[c++]=a[d];return b};Qa=function(a){var b=[],c=0,d;for(d in a)b[c++]=d;return b};_.Ra=function(a){var b={},c;for(c in a)b[c]=a[c];return b};Sa="constructor hasOwnProperty isPrototypeOf propertyIsEnumerable toLocaleString toString valueOf".split(" "); _.Ta=function(a,b){for(var c,d,e=1;e<arguments.length;e++){d=arguments[e];for(c in d)a[c]=d[c];for(var f=0;f<Sa.length;f++)c=Sa[f],Object.prototype.hasOwnProperty.call(d,c)&&(a[c]=d[c])}};
var Ua=function(){return(_.y("Chrome")||_.y("CriOS"))&&!_.y("Edge")};var Va,Wa;Va=function(){return _.y("iPhone")&&!_.y("iPod")&&!_.y("iPad")};Wa=function(){return Va()||_.y("iPad")||_.y("iPod")};_.Xa=function(){return _.y("Macintosh")};_.Ya=function(){return _.y("Windows")};_.Za=function(){return _.y("CrOS")};var $a=function(a){$a[" "](a);return a};$a[" "]=_.fa;_.ab=function(a,b){try{return $a(a[b]),!0}catch(c){}return!1};_.bb=function(a,b,c){return Object.prototype.hasOwnProperty.call(a,b)?a[b]:a[b]=c(b)};var cb,db,hb,kb,lb,pb,qb,sb;cb=_.y("Opera");_.z=_.y("Trident")||_.y("MSIE");db=_.y("Edge");_.eb=_.y("Gecko")&&!(-1!=_.Ka.toLowerCase().indexOf("webkit")&&!_.y("Edge"))&&!(_.y("Trident")||_.y("MSIE"))&&!_.y("Edge");_.fb=-1!=_.Ka.toLowerCase().indexOf("webkit")&&!_.y("Edge");hb=_.l.navigator||null;_.gb=hb&&hb.platform||"";_.ib=_.Xa();_.jb=_.Ya();kb=function(){var a=_.l.document;return a?a.documentMode:void 0};
a:{var mb="",nb=function(){var a=_.Ka;if(_.eb)return/rv:([^\);]+)(\)|;)/.exec(a);if(db)return/Edge\/([\d\.]+)/.exec(a);if(_.z)return/\b(?:MSIE|rv)[: ]([^\);]+)(\)|;)/.exec(a);if(_.fb)return/WebKit\/(\S+)/.exec(a);if(cb)return/(?:Version)[ \/]?(\S+)/.exec(a)}();nb&&(mb=nb?nb[1]:"");if(_.z){var ob=kb();if(null!=ob&&ob>(0,window.parseFloat)(mb)){lb=String(ob);break a}}lb=mb}pb=lb;qb={};_.rb=function(a){return _.bb(qb,a,function(){return 0<=_.ya(pb,a)})};var tb=_.l.document; sb=tb&&_.z?kb()||("CSS1Compat"==tb.compatMode?(0,window.parseInt)(pb,10):5):void 0;
var ub=_.y("Firefox"),vb=Va()||_.y("iPod"),wb=_.y("iPad"),xb=_.y("Android")&&!(Ua()||_.y("Firefox")||_.y("Opera")||_.y("Silk")),yb=Ua(),zb=_.y("Safari")&&!(Ua()||_.y("Coast")||_.y("Opera")||_.y("Edge")||_.y("Silk")||_.y("Android"))&&!Wa();var Ab=null;var Db,Eb,Hb;_.A=function(){};_.Bb="function"==typeof window.Uint8Array;_.B=function(a,b,c,d,e){a.b=null;b||(b=c?[c]:[]);a.o=c?String(c):void 0;a.h=0===c?-1:0;a.g=b;a:{if(a.g.length&&(b=a.g.length-1,(c=a.g[b])&&"object"==typeof c&&!_.t(c)&&!(_.Bb&&c instanceof window.Uint8Array))){a.j=b-a.h;a.c=c;break a}a.j=Number.MAX_VALUE}a.m={};if(d)for(b=0;b<d.length;b++)c=d[b],c<a.j?(c+=a.h,a.g[c]=a.g[c]||_.Cb):(Db(a),a.c[c]=a.c[c]||_.Cb);e&&e.length&&(0,_.x)(e,_.na(Eb,a))};_.Cb=[];
Db=function(a){var b=a.j+a.h;a.g[b]||(a.c=a.g[b]={})};_.C=function(a,b){if(b<a.j){b+=a.h;var c=a.g[b];return c===_.Cb?a.g[b]=[]:c}if(a.c)return c=a.c[b],c===_.Cb?a.c[b]=[]:c};_.Fb=function(a,b,c){a=_.C(a,b);return null==a?c:a};_.D=function(a,b,c){b<a.j?a.g[b+a.h]=c:(Db(a),a.c[b]=c)};Eb=function(a,b){var c,d;(0,_.x)(b,function(b){var e=_.C(a,b);null!=e&&(c=b,d=e,_.D(a,b,void 0))});return c?(_.D(a,c,d),c):0};_.E=function(a,b,c){a.b||(a.b={});if(!a.b[c]){var d=_.C(a,c);d&&(a.b[c]=new b(d))}return a.b[c]};
_.F=function(a,b,c){a.b||(a.b={});var d=c?_.Gb(c):c;a.b[b]=c;_.D(a,b,d)};Hb=function(a){if(a.b)for(var b in a.b){var c=a.b[b];if(_.t(c))for(var d=0;d<c.length;d++)c[d]&&_.Gb(c[d]);else c&&_.Gb(c)}};_.Gb=function(a){Hb(a);return a.g};
_.A.prototype.D=_.Bb?function(){var a=window.Uint8Array.prototype.toJSON;window.Uint8Array.prototype.toJSON=function(){if(!Ab){Ab={};for(var a=0;65>a;a++)Ab[a]="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/=".charAt(a)}a=Ab;for(var b=[],e=0;e<this.length;e+=3){var f=this[e],h=e+1<this.length,k=h?this[e+1]:0,n=e+2<this.length,r=n?this[e+2]:0,w=f>>2;f=(f&3)<<4|k>>4;k=(k&15)<<2|r>>6;r&=63;n||(r=64,h||(k=64));b.push(a[w],a[f],a[k],a[r])}return b.join("")};try{var b=JSON.stringify(_.Gb(this),
Ib)}finally{window.Uint8Array.prototype.toJSON=a}return b}:function(){return JSON.stringify(_.Gb(this),Ib)};var Ib=function(a,b){if(_.da(b)){if((0,window.isNaN)(b))return"NaN";if(window.Infinity===b)return"Infinity";if(-window.Infinity===b)return"-Infinity"}return b};_.A.prototype.toString=function(){Hb(this);return this.g.toString()};
_.G=function(){this.G=this.G;this.D=this.D};_.G.prototype.G=!1;_.G.prototype.$=function(){this.G||(this.G=!0,this.v())};_.J=function(a,b){_.H(a,_.na(_.I,b))};_.H=function(a,b,c){a.G?_.p(c)?b.call(c):b():(a.D||(a.D=[]),a.D.push(_.p(c)?(0,_.u)(b,c):b))};_.G.prototype.v=function(){if(this.D)for(;this.D.length;)this.D.shift()()};_.I=function(a){a&&"function"==typeof a.$&&a.$()};
var Jb=function(a,b,c){this.c=c;this.g=a;this.h=b;this.b=0;this.a=null};Jb.prototype.get=function(){if(0<this.b){this.b--;var a=this.a;this.a=a.next;a.next=null}else a=this.g();return a};var Kb=function(a,b){a.h(b);a.b<a.c&&(a.b++,b.next=a.a,a.a=b)};var Ob;_.Lb=[];_.Mb=[];_.Nb=!1;Ob=function(a){_.Lb[_.Lb.length]=a;if(_.Nb)for(var b=0;b<_.Mb.length;b++)a((0,_.u)(_.Mb[b].b,_.Mb[b]))};_.Pb=function(a){return function(){return a}}(!1);var Qb,Sb,Tb,Rb;Qb=function(a){_.l.setTimeout(function(){throw a;},0)};_.Ub=function(a,b){var c=a;b&&(c=(0,_.u)(a,b));c=Rb(c);!_.ja(_.l.setImmediate)||_.l.Window&&_.l.Window.prototype&&!_.y("Edge")&&_.l.Window.prototype.setImmediate==_.l.setImmediate?(Sb||(Sb=Tb()),Sb(c)):_.l.setImmediate(c)};
Tb=function(){var a=_.l.MessageChannel;"undefined"===typeof a&&"undefined"!==typeof window&&window.postMessage&&window.addEventListener&&!_.y("Presto")&&(a=function(){var a=window.document.createElement("IFRAME");a.style.display="none";a.src="";window.document.documentElement.appendChild(a);var b=a.contentWindow;a=b.document;a.open();a.write("");a.close();var c="callImmediate"+Math.random(),d="file:"==b.location.protocol?"*":b.location.protocol+"//"+b.location.host;a=(0,_.u)(function(a){if(("*"==
d||a.origin==d)&&a.data==c)this.port1.onmessage()},this);b.addEventListener("message",a,!1);this.port1={};this.port2={postMessage:function(){b.postMessage(c,d)}}});if("undefined"!==typeof a&&!_.y("Trident")&&!_.y("MSIE")){var b=new a,c={},d=c;b.port1.onmessage=function(){if(_.p(c.next)){c=c.next;var a=c.zb;c.zb=null;a()}};return function(a){d.next={zb:a};d=d.next;b.port2.postMessage(0)}}return"undefined"!==typeof window.document&&"onreadystatechange"in window.document.createElement("SCRIPT")?function(a){var b=
window.document.createElement("SCRIPT");b.onreadystatechange=function(){b.onreadystatechange=null;b.parentNode.removeChild(b);b=null;a();a=null};window.document.documentElement.appendChild(b)}:function(a){_.l.setTimeout(a,0)}};Rb=function(a){return a};Ob(function(a){Rb=a});
var Vb=function(){this.b=this.a=null},Xb=new Jb(function(){return new Wb},function(a){a.reset()},100);Vb.prototype.add=function(a,b){var c=Xb.get();c.set(a,b);this.b?this.b.next=c:this.a=c;this.b=c};Vb.prototype.remove=function(){var a=null;this.a&&(a=this.a,this.a=this.a.next,this.a||(this.b=null),a.next=null);return a};var Wb=function(){this.next=this.b=this.a=null};Wb.prototype.set=function(a,b){this.a=a;this.b=b;this.next=null};Wb.prototype.reset=function(){this.next=this.b=this.a=null};
var bc=function(a,b){Yb||Zb();$b||(Yb(),$b=!0);ac.add(a,b)},Yb,Zb=function(){if(-1!=String(_.l.Promise).indexOf("[native code]")){var a=_.l.Promise.resolve(void 0);Yb=function(){a.then(cc)}}else Yb=function(){_.Ub(cc)}},$b=!1,ac=new Vb,cc=function(){for(var a;a=ac.remove();){try{a.a.call(a.b)}catch(b){Qb(b)}Kb(Xb,a)}$b=!1};
var dc=function(a){a.prototype.then=a.prototype.then;a.prototype.$goog_Thenable=!0},ec=function(a){if(!a)return!1;try{return!!a.$goog_Thenable}catch(b){return!1}};var hc,ic,jc,oc,sc,tc,rc,pc;_.gc=function(a,b){this.a=0;this.D=void 0;this.c=this.b=this.g=null;this.h=this.j=!1;if(a!=_.fa)try{var c=this;a.call(b,function(a){_.fc(c,2,a)},function(a){_.fc(c,3,a)})}catch(d){_.fc(this,3,d)}};hc=function(){this.next=this.c=this.b=this.h=this.a=null;this.g=!1};hc.prototype.reset=function(){this.c=this.b=this.h=this.a=null;this.g=!1};ic=new Jb(function(){return new hc},function(a){a.reset()},100);jc=function(a,b,c){var d=ic.get();d.h=a;d.b=b;d.c=c;return d};
_.lc=function(){var a,b=new _.gc(function(b){a=b});return new kc(b,a)};_.gc.prototype.then=function(a,b,c){return _.mc(this,_.ja(a)?a:null,_.ja(b)?b:null,c)};dc(_.gc);_.gc.prototype.cancel=function(a){0==this.a&&bc(function(){var b=new nc(a);oc(this,b)},this)};
oc=function(a,b){if(0==a.a)if(a.g){var c=a.g;if(c.b){for(var d=0,e=null,f=null,h=c.b;h&&(h.g||(d++,h.a==a&&(e=h),!(e&&1<d)));h=h.next)e||(f=h);e&&(0==c.a&&1==d?oc(c,b):(f?(d=f,d.next==c.c&&(c.c=d),d.next=d.next.next):pc(c),qc(c,e,3,b)))}a.g=null}else _.fc(a,3,b)};sc=function(a,b){a.b||2!=a.a&&3!=a.a||rc(a);a.c?a.c.next=b:a.b=b;a.c=b};
_.mc=function(a,b,c,d){var e=jc(null,null,null);e.a=new _.gc(function(a,h){e.h=b?function(c){try{var e=b.call(d,c);a(e)}catch(r){h(r)}}:a;e.b=c?function(b){try{var e=c.call(d,b);!_.p(e)&&b instanceof nc?h(b):a(e)}catch(r){h(r)}}:h});e.a.g=a;sc(a,e);return e.a};_.gc.prototype.m=function(a){this.a=0;_.fc(this,2,a)};_.gc.prototype.o=function(a){this.a=0;_.fc(this,3,a)};
_.fc=function(a,b,c){if(0==a.a){a===c&&(b=3,c=new TypeError("Promise cannot resolve to itself"));a.a=1;a:{var d=c,e=a.m,f=a.o;if(d instanceof _.gc){sc(d,jc(e||_.fa,f||null,a));var h=!0}else if(ec(d))d.then(e,f,a),h=!0;else{if(_.ka(d))try{var k=d.then;if(_.ja(k)){tc(d,k,e,f,a);h=!0;break a}}catch(n){f.call(a,n);h=!0;break a}h=!1}}h||(a.D=c,a.a=b,a.g=null,rc(a),3!=b||c instanceof nc||uc(a,c))}};
tc=function(a,b,c,d,e){var f=!1,h=function(a){f||(f=!0,c.call(e,a))},k=function(a){f||(f=!0,d.call(e,a))};try{b.call(a,h,k)}catch(n){k(n)}};rc=function(a){a.j||(a.j=!0,bc(a.l,a))};pc=function(a){var b=null;a.b&&(b=a.b,a.b=b.next,b.next=null);a.b||(a.c=null);return b};_.gc.prototype.l=function(){for(var a;a=pc(this);)qc(this,a,this.a,this.D);this.j=!1};
var qc=function(a,b,c,d){if(3==c&&b.b&&!b.g)for(;a&&a.h;a=a.g)a.h=!1;if(b.a)b.a.g=null,vc(b,c,d);else try{b.g?b.h.call(b.c):vc(b,c,d)}catch(e){wc.call(null,e)}Kb(ic,b)},vc=function(a,b,c){2==b?a.h.call(a.c,c):a.b&&a.b.call(a.c,c)},uc=function(a,b){a.h=!0;bc(function(){a.h&&wc.call(null,b)})},wc=Qb,nc=function(a){_.pa.call(this,a)};_.v(nc,_.pa);nc.prototype.name="cancel";var kc=function(a,b){this.a=a;this.b=b};
/*
 Portions of this code are from MochiKit, received by
 The Closure Authors under the MIT license. All other code is Copyright
 2005-2009 The Closure Authors. All Rights Reserved.
*/
_.xc=function(a,b){this.D=[];this.C=a;this.H=b||null;this.h=this.ka=!1;this.c=void 0;this.o=this.F=this.m=!1;this.l=0;this.a=null;this.j=0};_.xc.prototype.cancel=function(a){if(this.ka)this.c instanceof _.xc&&this.c.cancel();else{if(this.a){var b=this.a;delete this.a;a?b.cancel(a):(b.j--,0>=b.j&&b.cancel())}this.C?this.C.call(this.H,this):this.o=!0;this.ka||this.w(new _.yc)}};_.xc.prototype.J=function(a,b){this.m=!1;zc(this,a,b)};
var zc=function(a,b,c){a.ka=!0;a.c=c;a.h=!b;Ac(a)},Cc=function(a){if(a.ka){if(!a.o)throw new Bc;a.o=!1}};_.xc.prototype.g=function(a){Cc(this);zc(this,!0,a)};_.xc.prototype.w=function(a){Cc(this);zc(this,!1,a)};_.Ec=function(a,b,c){_.Dc(a,b,null,c)};_.Dc=function(a,b,c,d){a.D.push([b,c,d]);a.ka&&Ac(a)};_.xc.prototype.then=function(a,b,c){var d,e,f=new _.gc(function(a,b){d=a;e=b});_.Dc(this,d,function(a){a instanceof _.yc?f.cancel():e(a)});return f.then(a,b,c)};dc(_.xc);
_.xc.prototype.b=function(a){var b=new _.xc;_.Dc(this,b.g,b.w,b);a&&(b.a=this,this.j++);return b};_.xc.prototype.isError=function(a){return a instanceof Error};
var Fc=function(a){return(0,_.Ca)(a.D,function(a){return _.ja(a[1])})},Ac=function(a){if(a.l&&a.ka&&Fc(a)){var b=a.l,c=Gc[b];c&&(_.l.clearTimeout(c.a),delete Gc[b]);a.l=0}a.a&&(a.a.j--,delete a.a);b=a.c;for(var d=c=!1;a.D.length&&!a.m;){var e=a.D.shift(),f=e[0],h=e[1];e=e[2];if(f=a.h?h:f)try{var k=f.call(e||a.H,b);_.p(k)&&(a.h=a.h&&(k==b||a.isError(k)),a.c=b=k);if(ec(b)||"function"===typeof _.l.Promise&&b instanceof _.l.Promise)d=!0,a.m=!0}catch(n){b=n,a.h=!0,Fc(a)||(c=!0)}}a.c=b;d&&(k=(0,_.u)(a.J,
a,!0),d=(0,_.u)(a.J,a,!1),b instanceof _.xc?(_.Dc(b,k,d),b.F=!0):b.then(k,d));c&&(b=new Hc(b),Gc[b.a]=b,a.l=b.a)},Bc=function(){_.pa.call(this)};_.v(Bc,_.pa);Bc.prototype.message="Deferred has already fired";Bc.prototype.name="AlreadyCalledError";_.yc=function(){_.pa.call(this)};_.v(_.yc,_.pa);_.yc.prototype.message="Deferred was canceled";_.yc.prototype.name="CanceledError";var Hc=function(a){this.a=_.l.setTimeout((0,_.u)(this.g,this),0);this.b=a}; Hc.prototype.g=function(){delete Gc[this.a];throw this.b;};var Gc={};
_.Ic=!_.z||9<=Number(sb);_.Jc=!_.eb&&!_.z||_.z&&9<=Number(sb)||_.eb&&_.rb("1.9.1");_.z&&_.rb("9");_.Kc=/^(ar|ckb|dv|he|iw|fa|nqo|ps|sd|ug|ur|yi|.*[-_](Arab|Hebr|Thaa|Nkoo|Tfng))(?!.*[-_](Latn|Cyrl)($|-|_))($|-|_)/i;_.Mc=function(){this.a="";this.b=_.Lc};_.Mc.prototype.Ga=!0;_.Mc.prototype.Ea=function(){return this.a};_.Mc.prototype.qb=!0;_.Mc.prototype.Ra=function(){return 1};_.Lc={};_.Nc=function(a){var b=new _.Mc;b.a=a;return b};_.Nc("about:blank");_.Pc=function(){this.a="";this.g=_.Oc;this.b=null};_.Pc.prototype.qb=!0;_.Pc.prototype.Ra=function(){return this.b};_.Pc.prototype.Ga=!0;_.Pc.prototype.Ea=function(){return this.a};_.Oc={};_.Qc=function(a,b){var c=new _.Pc;c.a=a;c.b=b;return c};_.Qc("<!DOCTYPE html>",0);_.Qc("",0);_.Rc=_.Qc("<br>",0);
var Uc;_.Tc=function(a,b){var c=b||window.document;if(c.getElementsByClassName)a=c.getElementsByClassName(a)[0];else{c=window.document;var d=b||c;a=d.querySelectorAll&&d.querySelector&&a?d.querySelector(""+(a?"."+a:"")):_.Sc(c,"*",a,b)[0]||null}return a||null};
_.Sc=function(a,b,c,d){a=d||a;b=b&&"*"!=b?String(b).toUpperCase():"";if(a.querySelectorAll&&a.querySelector&&(b||c))return a.querySelectorAll(b+(c?"."+c:""));if(c&&a.getElementsByClassName){a=a.getElementsByClassName(c);if(b){d={};for(var e=0,f=0,h;h=a[f];f++)b==h.nodeName&&(d[e++]=h);d.length=e;return d}return a}a=a.getElementsByTagName(b||"*");if(c){d={};for(f=e=0;h=a[f];f++)b=h.className,"function"==typeof b.split&&_.Fa(b.split(/\s+/),c)&&(d[e++]=h);d.length=e;return d}return a};
_.Vc=function(a,b){_.Na(b,function(b,d){b&&b.Ga&&(b=b.Ea());"style"==d?a.style.cssText=b:"class"==d?a.className=b:"for"==d?a.htmlFor=b:Uc.hasOwnProperty(d)?a.setAttribute(Uc[d],b):_.qa(d,"aria-")||_.qa(d,"data-")?a.setAttribute(d,b):a[d]=b})};Uc={cellpadding:"cellPadding",cellspacing:"cellSpacing",colspan:"colSpan",frameborder:"frameBorder",height:"height",maxlength:"maxLength",nonce:"nonce",role:"role",rowspan:"rowSpan",type:"type",usemap:"useMap",valign:"vAlign",width:"width"}; _.Wc=function(a){for(var b;b=a.firstChild;)a.removeChild(b)};
var Yc,Xc,ad,bd,$c;_.Zc=function(a){var b=[];Xc(new Yc,a,b);return b.join("")};Yc=function(){};
Xc=function(a,b,c){if(null==b)c.push("null");else{if("object"==typeof b){if(_.t(b)){var d=b;b=d.length;c.push("[");for(var e="",f=0;f<b;f++)c.push(e),Xc(a,d[f],c),e=",";c.push("]");return}if(b instanceof String||b instanceof Number||b instanceof Boolean)b=b.valueOf();else{c.push("{");e="";for(d in b)Object.prototype.hasOwnProperty.call(b,d)&&(f=b[d],"function"!=typeof f&&(c.push(e),$c(d,c),c.push(":"),Xc(a,f,c),e=","));c.push("}");return}}switch(typeof b){case "string":$c(b,c);break;case "number":c.push((0,window.isFinite)(b)&&
!(0,window.isNaN)(b)?String(b):"null");break;case "boolean":c.push(String(b));break;case "function":c.push("null");break;default:throw Error("d`"+typeof b);}}};ad={'"':'\\"',"\\":"\\\\","/":"\\/","\b":"\\b","\f":"\\f","\n":"\\n","\r":"\\r","\t":"\\t","\x0B":"\\u000b"};bd=/\uffff/.test("\uffff")?/[\\"\x00-\x1f\x7f-\uffff]/g:/[\\"\x00-\x1f\x7f-\xff]/g;$c=function(a,b){b.push('"',a.replace(bd,function(a){var b=ad[a];b||(b="\\u"+(a.charCodeAt(0)|65536).toString(16).substr(1),ad[a]=b);return b}),'"')};
var cd="StopIteration"in _.l?_.l.StopIteration:{message:"StopIteration",stack:""},dd=function(){};dd.prototype.next=function(){throw cd;};dd.prototype.ha=function(){return this};
var ed=function(a){if(a instanceof dd)return a;if("function"==typeof a.ha)return a.ha(!1);if(_.ia(a)){var b=0,c=new dd;c.next=function(){for(;;){if(b>=a.length)throw cd;if(b in a)return a[b++];b++}};return c}throw Error("e");},fd=function(a,b){if(_.ia(a))try{(0,_.x)(a,b,void 0)}catch(c){if(c!==cd)throw c;}else{a=ed(a);try{for(;;)b.call(void 0,a.next(),void 0,a)}catch(c){if(c!==cd)throw c;}}},gd=function(a){if(_.ia(a))return _.Ja(a);a=ed(a);var b=[];fd(a,function(a){b.push(a)});return b};
_.K=function(a,b){this.b={};this.a=[];this.c=this.g=0;var c=arguments.length;if(1<c){if(c%2)throw Error("b");for(var d=0;d<c;d+=2)this.set(arguments[d],arguments[d+1])}else if(a){a instanceof _.K?(c=a.W(),d=a.R()):(c=Qa(a),d=Pa(a));for(var e=0;e<c.length;e++)this.set(c[e],d[e])}};_.K.prototype.R=function(){hd(this);for(var a=[],b=0;b<this.a.length;b++)a.push(this.b[this.a[b]]);return a};_.K.prototype.W=function(){hd(this);return this.a.concat()};_.jd=function(a,b){return id(a.b,b)};
_.K.prototype.clear=function(){this.b={};this.c=this.g=this.a.length=0};_.K.prototype.remove=function(a){return id(this.b,a)?(delete this.b[a],this.g--,this.c++,this.a.length>2*this.g&&hd(this),!0):!1};var hd=function(a){if(a.g!=a.a.length){for(var b=0,c=0;b<a.a.length;){var d=a.a[b];id(a.b,d)&&(a.a[c++]=d);b++}a.a.length=c}if(a.g!=a.a.length){var e={};for(c=b=0;b<a.a.length;)d=a.a[b],id(e,d)||(a.a[c++]=d,e[d]=1),b++;a.a.length=c}};_.K.prototype.get=function(a,b){return id(this.b,a)?this.b[a]:b};
_.K.prototype.set=function(a,b){id(this.b,a)||(this.g++,this.a.push(a),this.c++);this.b[a]=b};_.K.prototype.forEach=function(a,b){for(var c=this.W(),d=0;d<c.length;d++){var e=c[d],f=this.get(e);a.call(b,f,e,this)}};_.K.prototype.ha=function(a){hd(this);var b=0,c=this.c,d=this,e=new dd;e.next=function(){if(c!=d.c)throw Error("f");if(b>=d.a.length)throw cd;var e=d.a[b++];return a?e:d.b[e]};return e};var id=function(a,b){return Object.prototype.hasOwnProperty.call(a,b)};
_.ld=function(a,b){this.type="undefined"!=typeof _.kd&&a instanceof _.kd?String(a):a;this.b=this.target=b;this.c=!1;this.Eb=!0};_.ld.prototype.h=function(){this.c=!0};_.ld.prototype.g=function(){this.Eb=!1};var md=!_.z||9<=Number(sb),nd=_.z&&!_.rb("9");!_.fb||_.rb("528");_.eb&&_.rb("1.9b")||_.z&&_.rb("8")||cb&&_.rb("9.5")||_.fb&&_.rb("528");_.eb&&!_.rb("8")||_.z&&_.rb("9");var od=function(){if(!_.l.addEventListener||!Object.defineProperty)return!1;var a=!1,b=Object.defineProperty({},"passive",{get:function(){a=!0}});_.l.addEventListener("test",_.fa,b);_.l.removeEventListener("test",_.fa,b);return a}();
var qd=function(a,b){_.ld.call(this,a?a.type:"");this.relatedTarget=this.b=this.target=null;this.button=this.screenY=this.screenX=this.clientY=this.clientX=0;this.key="";this.keyCode=0;this.metaKey=this.shiftKey=this.altKey=this.ctrlKey=!1;this.state=null;this.pointerId=0;this.pointerType="";this.a=null;if(a){var c=this.type=a.type,d=a.changedTouches?a.changedTouches[0]:null;this.target=a.target||a.srcElement;this.b=b;(b=a.relatedTarget)?_.eb&&(_.ab(b,"nodeName")||(b=null)):"mouseover"==c?b=a.fromElement:
"mouseout"==c&&(b=a.toElement);this.relatedTarget=b;null===d?(this.clientX=void 0!==a.clientX?a.clientX:a.pageX,this.clientY=void 0!==a.clientY?a.clientY:a.pageY,this.screenX=a.screenX||0,this.screenY=a.screenY||0):(this.clientX=void 0!==d.clientX?d.clientX:d.pageX,this.clientY=void 0!==d.clientY?d.clientY:d.pageY,this.screenX=d.screenX||0,this.screenY=d.screenY||0);this.button=a.button;this.keyCode=a.keyCode||0;this.key=a.key||"";this.ctrlKey=a.ctrlKey;this.altKey=a.altKey;this.shiftKey=a.shiftKey;
this.metaKey=a.metaKey;this.pointerId=a.pointerId||0;this.pointerType=_.q(a.pointerType)?a.pointerType:pd[a.pointerType]||"";this.state=a.state;this.a=a;a.defaultPrevented&&this.g()}};_.v(qd,_.ld);var pd={2:"touch",3:"pen",4:"mouse"};qd.prototype.h=function(){qd.A.h.call(this);this.a.stopPropagation?this.a.stopPropagation():this.a.cancelBubble=!0}; qd.prototype.g=function(){qd.A.g.call(this);var a=this.a;if(a.preventDefault)a.preventDefault();else if(a.returnValue=!1,nd)try{if(a.ctrlKey||112<=a.keyCode&&123>=a.keyCode)a.keyCode=-1}catch(b){}};
var rd="closure_listenable_"+(1E6*Math.random()|0),sd=function(a){return!(!a||!a[rd])},td=0;var ud=function(a,b,c,d,e){this.listener=a;this.proxy=null;this.src=b;this.type=c;this.capture=!!d;this.Ta=e;this.key=++td;this.removed=this.Pa=!1},vd=function(a){a.removed=!0;a.listener=null;a.proxy=null;a.src=null;a.Ta=null};var wd=function(a){this.src=a;this.a={};this.b=0};wd.prototype.add=function(a,b,c,d,e){var f=a.toString();a=this.a[f];a||(a=this.a[f]=[],this.b++);var h=xd(a,b,d,e);-1<h?(b=a[h],c||(b.Pa=!1)):(b=new ud(b,this.src,f,!!d,e),b.Pa=c,a.push(b));return b};wd.prototype.remove=function(a,b,c,d){a=a.toString();if(!(a in this.a))return!1;var e=this.a[a];b=xd(e,b,c,d);return-1<b?(vd(e[b]),_.Ga(e,b),0==e.length&&(delete this.a[a],this.b--),!0):!1};
var yd=function(a,b){var c=b.type;c in a.a&&_.Ha(a.a[c],b)&&(vd(b),0==a.a[c].length&&(delete a.a[c],a.b--))};wd.prototype.removeAll=function(a){a=a&&a.toString();var b=0,c;for(c in this.a)if(!a||c==a){for(var d=this.a[c],e=0;e<d.length;e++)++b,vd(d[e]);delete this.a[c];this.b--}return b};
var zd=function(a,b,c,d,e){a=a.a[b.toString()];b=-1;a&&(b=xd(a,c,d,e));return-1<b?a[b]:null},Ad=function(a){var b=_.p(void 0)?"undefined":void 0,c=_.p(b),d=c?b.toString():"",e=_.p(void 0);return Oa(a.a,function(a){for(var b=0;b<a.length;++b)if(!(c&&a[b].type!=d||e&&void 0!=a[b].capture))return!0;return!1})},xd=function(a,b,c,d){for(var e=0;e<a.length;++e){var f=a[e];if(!f.removed&&f.listener==b&&f.capture==!!c&&f.Ta==d)return e}return-1};
var Bd,Cd,Dd,Hd,Jd,Nd,Kd,Pd,Od,Ld,Id,Qd,Gd;Bd="closure_lm_"+(1E6*Math.random()|0);Cd={};Dd=0;_.Fd=function(a,b,c,d,e){if(d&&d.once)return _.Ed(a,b,c,d,e);if(_.t(b)){for(var f=0;f<b.length;f++)_.Fd(a,b[f],c,d,e);return null}c=Gd(c);return sd(a)?a.listen(b,c,_.ka(d)?!!d.capture:!!d,e):Hd(a,b,c,!1,d,e)};
Hd=function(a,b,c,d,e,f){if(!b)throw Error("g");var h=_.ka(e)?!!e.capture:!!e,k=Id(a);k||(a[Bd]=k=new wd(a));c=k.add(b,c,d,h,f);if(c.proxy)return c;d=Jd();c.proxy=d;d.src=a;d.listener=c;if(a.addEventListener)od||(e=h),void 0===e&&(e=!1),a.addEventListener(b.toString(),d,e);else if(a.attachEvent)a.attachEvent(Kd(b.toString()),d);else throw Error("h");Dd++;return c};Jd=function(){var a=Ld,b=md?function(c){return a.call(b.src,b.listener,c)}:function(c){c=a.call(b.src,b.listener,c);if(!c)return c};return b};
_.Ed=function(a,b,c,d,e){if(_.t(b)){for(var f=0;f<b.length;f++)_.Ed(a,b[f],c,d,e);return null}c=Gd(c);return sd(a)?a.Sa(b,c,_.ka(d)?!!d.capture:!!d,e):Hd(a,b,c,!0,d,e)};_.Md=function(a,b,c,d,e){if(_.t(b))for(var f=0;f<b.length;f++)_.Md(a,b[f],c,d,e);else d=_.ka(d)?!!d.capture:!!d,c=Gd(c),sd(a)?a.Va(b,c,d,e):a&&(a=Id(a))&&(b=zd(a,b,c,d,e))&&Nd(b)};
Nd=function(a){if(!_.da(a)&&a&&!a.removed){var b=a.src;if(sd(b))yd(b.g,a);else{var c=a.type,d=a.proxy;b.removeEventListener?b.removeEventListener(c,d,a.capture):b.detachEvent&&b.detachEvent(Kd(c),d);Dd--;(c=Id(b))?(yd(c,a),0==c.b&&(c.src=null,b[Bd]=null)):vd(a)}}};Kd=function(a){return a in Cd?Cd[a]:Cd[a]="on"+a};Pd=function(a,b,c,d){var e=!0;if(a=Id(a))if(b=a.a[b.toString()])for(b=b.concat(),a=0;a<b.length;a++){var f=b[a];f&&f.capture==c&&!f.removed&&(f=Od(f,d),e=e&&!1!==f)}return e};
Od=function(a,b){var c=a.listener,d=a.Ta||a.src;a.Pa&&Nd(a);return c.call(d,b)};
Ld=function(a,b){if(a.removed)return!0;if(!md){var c=b||_.ea("window.event");b=new qd(c,this);var d=!0;if(!(0>c.keyCode||void 0!=c.returnValue)){a:{var e=!1;if(0==c.keyCode)try{c.keyCode=-1;break a}catch(h){e=!0}if(e||void 0==c.returnValue)c.returnValue=!0}c=[];for(e=b.b;e;e=e.parentNode)c.push(e);a=a.type;for(e=c.length-1;!b.c&&0<=e;e--){b.b=c[e];var f=Pd(c[e],a,!0,b);d=d&&f}for(e=0;!b.c&&e<c.length;e++)b.b=c[e],f=Pd(c[e],a,!1,b),d=d&&f}return d}return Od(a,new qd(b,this))}; Id=function(a){a=a[Bd];return a instanceof wd?a:null};Qd="__closure_events_fn_"+(1E9*Math.random()>>>0);Gd=function(a){if(_.ja(a))return a;a[Qd]||(a[Qd]=function(b){return a.handleEvent(b)});return a[Qd]};Ob(function(a){Ld=a(Ld)});
_.L=function(){_.G.call(this);this.g=new wd(this);this.ba=this;this.J=null};_.v(_.L,_.G);_.L.prototype[rd]=!0;_.L.prototype.H=function(a){this.J=a};_.L.prototype.removeEventListener=function(a,b,c,d){_.Md(this,a,b,c,d)};
_.M=function(a,b){var c,d=a.J;if(d)for(c=[];d;d=d.J)c.push(d);a=a.ba;d=b.type||b;if(_.q(b))b=new _.ld(b,a);else if(b instanceof _.ld)b.target=b.target||a;else{var e=b;b=new _.ld(d,a);_.Ta(b,e)}e=!0;if(c)for(var f=c.length-1;!b.c&&0<=f;f--){var h=b.b=c[f];e=h.qa(d,!0,b)&&e}b.c||(h=b.b=a,e=h.qa(d,!0,b)&&e,b.c||(e=h.qa(d,!1,b)&&e));if(c)for(f=0;!b.c&&f<c.length;f++)h=b.b=c[f],e=h.qa(d,!1,b)&&e;return e};_.g=_.L.prototype;_.g.v=function(){_.L.A.v.call(this);this.g&&this.g.removeAll(void 0);this.J=null};
_.g.listen=function(a,b,c,d){return this.g.add(String(a),b,!1,c,d)};_.g.Sa=function(a,b,c,d){return this.g.add(String(a),b,!0,c,d)};_.g.Va=function(a,b,c,d){return this.g.remove(String(a),b,c,d)};_.g.qa=function(a,b,c){a=this.g.a[String(a)];if(!a)return!0;a=a.concat();for(var d=!0,e=0;e<a.length;++e){var f=a[e];if(f&&!f.removed&&f.capture==b){var h=f.listener,k=f.Ta||f.src;f.Pa&&yd(this.g,f);d=!1!==h.call(k,c)&&d}}return d&&0!=c.Eb};
var Rd=function(){};Rd.prototype.a=null;var Td=function(a){var b;(b=a.a)||(b={},Sd(a)&&(b[0]=!0,b[1]=!0),b=a.a=b);return b};var Ud,Vd=function(){};_.v(Vd,Rd);var Wd=function(a){return(a=Sd(a))?new window.ActiveXObject(a):new window.XMLHttpRequest},Sd=function(a){if(!a.b&&"undefined"==typeof window.XMLHttpRequest&&"undefined"!=typeof window.ActiveXObject){for(var b=["MSXML2.XMLHTTP.6.0","MSXML2.XMLHTTP.3.0","MSXML2.XMLHTTP","Microsoft.XMLHTTP"],c=0;c<b.length;c++){var d=b[c];try{return new window.ActiveXObject(d),a.b=d}catch(e){}}throw Error("i");}return a.b};Ud=new Vd;
var Yd;_.Xd=function(a){if(a.R&&"function"==typeof a.R)return a.R();if(_.q(a))return a.split("");if(_.ia(a)){for(var b=[],c=a.length,d=0;d<c;d++)b.push(a[d]);return b}return Pa(a)};
Yd=function(a,b){if(a.forEach&&"function"==typeof a.forEach)a.forEach(b,void 0);else if(_.ia(a)||_.q(a))(0,_.x)(a,b,void 0);else{if(a.W&&"function"==typeof a.W)var c=a.W();else if(a.R&&"function"==typeof a.R)c=void 0;else if(_.ia(a)||_.q(a)){c=[];for(var d=a.length,e=0;e<d;e++)c.push(e)}else c=Qa(a);d=_.Xd(a);e=d.length;for(var f=0;f<e;f++)b.call(void 0,d[f],c&&c[f],a)}};
_.Zd=function(a,b){_.L.call(this);this.b=a||1;this.a=b||_.l;this.c=(0,_.u)(this.Ec,this);this.h=(0,_.m)()};_.v(_.Zd,_.L);_.g=_.Zd.prototype;_.g.ta=!1;_.g.X=null;_.g.setInterval=function(a){this.b=a;this.X&&this.ta?(this.stop(),this.start()):this.X&&this.stop()};_.g.Ec=function(){if(this.ta){var a=(0,_.m)()-this.h;0<a&&a<.8*this.b?this.X=this.a.setTimeout(this.c,this.b-a):(this.X&&(this.a.clearTimeout(this.X),this.X=null),_.M(this,"tick"),this.ta&&(this.X=this.a.setTimeout(this.c,this.b),this.h=(0,_.m)()))}};
_.g.start=function(){this.ta=!0;this.X||(this.X=this.a.setTimeout(this.c,this.b),this.h=(0,_.m)())};_.g.stop=function(){this.ta=!1;this.X&&(this.a.clearTimeout(this.X),this.X=null)};_.g.v=function(){_.Zd.A.v.call(this);this.stop();delete this.a};_.$d=function(a,b,c){if(_.ja(a))c&&(a=(0,_.u)(a,c));else if(a&&"function"==typeof a.handleEvent)a=(0,_.u)(a.handleEvent,a);else throw Error("j");return 2147483647<Number(b)?-1:_.l.setTimeout(a,b||0)};_.ae=function(a){_.l.clearTimeout(a)};
var be=/^(?:([^:/?#.]+):)?(?:\/\/(?:([^/?#]*)@)?([^/#?]*?)(?::([0-9]+))?(?=[/#?]|$))?([^?#]+)?(?:\?([^#]*))?(?:#([\s\S]*))?$/,ce=function(a,b){if(a){a=a.split("&");for(var c=0;c<a.length;c++){var d=a[c].indexOf("="),e=null;if(0<=d){var f=a[c].substring(0,d);e=a[c].substring(d+1)}else f=a[c];b(f,e?(0,window.decodeURIComponent)(e.replace(/\+/g," ")):"")}}};
var de=function(a){_.L.call(this);this.headers=new _.K;this.o=a||null;this.b=!1;this.m=this.a=null;this.F="";this.c=this.C=this.h=this.w=!1;this.l=0;this.j=null;this.V="";this.M=this.N=!1},ee,fe,ge,oe,ne,ke,pe;_.v(de,_.L);ee=/^https?$/i;fe=["POST","PUT"];ge=[];_.he=function(a,b,c,d,e,f,h){var k=new de;ge.push(k);b&&k.listen("complete",b);k.Sa("ready",k.Y);f&&(k.l=Math.max(0,f));h&&(k.N=h);k.send(a,c,d,e)};de.prototype.Y=function(){this.$();_.Ha(ge,this)};
de.prototype.send=function(a,b,c,d){if(this.a)throw Error("k`"+this.F+"`"+a);b=b?b.toUpperCase():"GET";this.F=a;this.w=!1;this.b=!0;this.a=this.o?Wd(this.o):Wd(Ud);this.m=this.o?Td(this.o):Td(Ud);this.a.onreadystatechange=(0,_.u)(this.T,this);try{this.C=!0,this.a.open(b,String(a),!0),this.C=!1}catch(f){ie(this);return}a=c||"";var e=new _.K(this.headers);d&&Yd(d,function(a,b){e.set(b,a)});d=_.Ea(e.W(),je);c=_.l.FormData&&a instanceof _.l.FormData;!_.Fa(fe,b)||d||c||e.set("Content-Type","application/x-www-form-urlencoded;charset=utf-8");
e.forEach(function(a,b){this.a.setRequestHeader(b,a)},this);this.V&&(this.a.responseType=this.V);"withCredentials"in this.a&&this.a.withCredentials!==this.N&&(this.a.withCredentials=this.N);try{ke(this),0<this.l&&((this.M=le(this.a))?(this.a.timeout=this.l,this.a.ontimeout=(0,_.u)(this.S,this)):this.j=_.$d(this.S,this.l,this)),this.h=!0,this.a.send(a),this.h=!1}catch(f){ie(this)}};var le=function(a){return _.z&&_.rb(9)&&_.da(a.timeout)&&_.p(a.ontimeout)},je=function(a){return"content-type"==a.toLowerCase()};
de.prototype.S=function(){"undefined"!=typeof _.aa&&this.a&&(_.M(this,"timeout"),this.abort(8))};var ie=function(a){a.b=!1;a.a&&(a.c=!0,a.a.abort(),a.c=!1);me(a);ne(a)},me=function(a){a.w||(a.w=!0,_.M(a,"complete"),_.M(a,"error"))};de.prototype.abort=function(){this.a&&this.b&&(this.b=!1,this.c=!0,this.a.abort(),this.c=!1,_.M(this,"complete"),_.M(this,"abort"),ne(this))};de.prototype.v=function(){this.a&&(this.b&&(this.b=!1,this.c=!0,this.a.abort(),this.c=!1),ne(this,!0));de.A.v.call(this)};
de.prototype.T=function(){this.G||(this.C||this.h||this.c?oe(this):this.L())};de.prototype.L=function(){oe(this)};oe=function(a){if(a.b&&"undefined"!=typeof _.aa&&(!a.m[1]||4!=(a.a?a.a.readyState:0)||2!=pe(a)))if(a.h&&4==(a.a?a.a.readyState:0))_.$d(a.T,0,a);else if(_.M(a,"readystatechange"),4==(a.a?a.a.readyState:0)){a.b=!1;try{_.qe(a)?(_.M(a,"complete"),_.M(a,"success")):me(a)}finally{ne(a)}}};
ne=function(a,b){if(a.a){ke(a);var c=a.a,d=a.m[0]?_.fa:null;a.a=null;a.m=null;b||_.M(a,"ready");try{c.onreadystatechange=d}catch(e){}}};ke=function(a){a.a&&a.M&&(a.a.ontimeout=null);a.j&&(_.ae(a.j),a.j=null)};
_.qe=function(a){var b=pe(a);a:switch(b){case 200:case 201:case 202:case 204:case 206:case 304:case 1223:var c=!0;break a;default:c=!1}if(!c){if(b=0===b)a=String(a.F).match(be)[1]||null,!a&&_.l.self&&_.l.self.location&&(a=_.l.self.location.protocol,a=a.substr(0,a.length-1)),b=!ee.test(a?a.toLowerCase():"");c=b}return c};pe=function(a){try{return 2<(a.a?a.a.readyState:0)?a.a.status:-1}catch(b){return-1}};Ob(function(a){de.prototype.L=a(de.prototype.L)});
var se;_.O=function(a){_.G.call(this);this.S=a;this.J={}};_.v(_.O,_.G);var re=[];_.O.prototype.listen=function(a,b,c,d){_.t(b)||(b&&(re[0]=b.toString()),b=re);for(var e=0;e<b.length;e++){var f=_.Fd(a,b[e],c||this.handleEvent,d||!1,this.S||this);if(!f)break;this.J[f.key]=f}return this};_.te=function(a,b,c,d){se(a,b,c,d,void 0)};se=function(a,b,c,d,e,f){if(_.t(c))for(var h=0;h<c.length;h++)se(a,b,c[h],d,e,f);else(b=_.Ed(b,c,d||a.handleEvent,e,f||a.S||a))&&(a.J[b.key]=b)};
_.O.prototype.Va=function(a,b,c,d,e){if(_.t(b))for(var f=0;f<b.length;f++)this.Va(a,b[f],c,d,e);else c=c||this.handleEvent,d=_.ka(d)?!!d.capture:!!d,e=e||this.S||this,c=Gd(c),d=!!d,b=sd(a)?zd(a.g,String(b),c,d,e):a?(a=Id(a))?zd(a,b,c,d,e):null:null,b&&(Nd(b),delete this.J[b.key]);return this};_.O.prototype.removeAll=function(){_.Na(this.J,function(a,b){this.J.hasOwnProperty(b)&&Nd(a)},this);this.J={}};_.O.prototype.v=function(){_.O.A.v.call(this);this.removeAll()}; _.O.prototype.handleEvent=function(){throw Error("l");};
_.ue=function(a){_.B(this,a,0,null,null)};_.v(_.ue,_.A);var we=function(a,b){var c=Array.prototype.slice.call(arguments),d=c.shift();if("undefined"==typeof d)throw Error("m");return d.replace(/%([0\- \+]*)(\d+)?(\.(\d+))?([%sfdiu])/g,function(a,b,d,k,n,r,w,N){if("%"==r)return"%";var e=c.shift();if("undefined"==typeof e)throw Error("n");arguments[0]=e;return ve[r].apply(null,arguments)})},ve={s:function(a,b,c){return(0,window.isNaN)(c)||""==c||a.length>=Number(c)?a:a=-1<b.indexOf("-",0)?a+va(" ",Number(c)-a.length):va(" ",Number(c)-a.length)+a},f:function(a,
b,c,d,e){d=a.toString();(0,window.isNaN)(e)||""==e||(d=(0,window.parseFloat)(a).toFixed(e));var f=0>Number(a)?"-":0<=b.indexOf("+")?"+":0<=b.indexOf(" ")?" ":"";0<=Number(a)&&(d=f+d);if((0,window.isNaN)(c)||d.length>=Number(c))return d;d=(0,window.isNaN)(e)?Math.abs(Number(a)).toString():Math.abs(Number(a)).toFixed(e);a=Number(c)-d.length-f.length;return d=0<=b.indexOf("-",0)?f+d+va(" ",a):f+va(0<=b.indexOf("0",0)?"0":" ",a)+d},d:function(a,b,c,d,e,f,h,k){return ve.f((0,window.parseInt)(a,10),b,c, d,0,f,h,k)}};ve.i=ve.d;ve.u=ve.d;
_.P=function(a,b){for(var c=[],d=0;d<arguments.length;d++)if(arguments[d]instanceof Error)c.push(arguments[d].stack);else if("object"==typeof arguments[d])try{c.push(JSON.stringify(arguments[d]))}catch(e){c.push("_error_("+e+")")}else c.push(arguments[d]);window.console&&(d=new Date,d=we("%02d-%02d ",d.getMonth()+1,d.getDate())+d.toLocaleTimeString(void 0,{hour12:!1})+we(".%03d",d.getMilliseconds()),window.console.log(d+" info: "+we.apply({},c)))};
_.ye=function(a){_.B(this,a,"h_exts",xe,null)};_.v(_.ye,_.A);var xe=[2];_.ye.messageId="h_exts";var ze,Ae,Be,Ee,Ge,Pe,He,Je,Ie,Me,Ke,Fe,Qe;_.Q=function(a,b){this.b=this.D=this.h="";this.c=null;this.l=this.a="";this.j=!1;var c;a instanceof _.Q?(this.j=_.p(b)?b:a.j,ze(this,a.h),this.D=a.D,this.b=a.b,Ae(this,a.c),this.a=a.a,Be(this,Ce(a.g)),_.De(this,a.l)):a&&(c=String(a).match(be))?(this.j=!!b,ze(this,c[1]||"",!0),this.D=Ee(c[2]||""),this.b=Ee(c[3]||"",!0),Ae(this,c[4]),this.a=Ee(c[5]||"",!0),Be(this,c[6]||"",!0),_.De(this,c[7]||"",!0)):(this.j=!!b,this.g=new Fe(null,0,this.j))};
_.Q.prototype.toString=function(){var a=[],b=this.h;b&&a.push(Ge(b,He,!0),":");var c=this.b;if(c||"file"==b)a.push("//"),(b=this.D)&&a.push(Ge(b,He,!0),"@"),a.push((0,window.encodeURIComponent)(String(c)).replace(/%25([0-9a-fA-F]{2})/g,"%$1")),c=this.c,null!=c&&a.push(":",String(c));if(c=this.a)this.b&&"/"!=c.charAt(0)&&a.push("/"),a.push(Ge(c,"/"==c.charAt(0)?Ie:Je,!0));(c=this.g.toString())&&a.push("?",c);(c=this.l)&&a.push("#",Ge(c,Ke));return a.join("")};
ze=function(a,b,c){a.h=c?Ee(b,!0):b;a.h&&(a.h=a.h.replace(/:$/,""))};Ae=function(a,b){if(b){b=Number(b);if((0,window.isNaN)(b)||0>b)throw Error("q`"+b);a.c=b}else a.c=null};Be=function(a,b,c){b instanceof Fe?(a.g=b,Le(a.g,a.j)):(c||(b=Ge(b,Me)),a.g=new Fe(b,0,a.j))};_.R=function(a,b,c){a.g.set(b,c)};_.De=function(a,b,c){a.l=c?Ee(b):b};_.Ne=function(a){return a instanceof _.Q?new _.Q(a):new _.Q(a,void 0)};
_.Oe=function(a,b){a instanceof _.Q||(a=_.Ne(a));b instanceof _.Q||(b=_.Ne(b));var c=a;a=new _.Q(c);var d=!!b.h;d?ze(a,b.h):d=!!b.D;d?a.D=b.D:d=!!b.b;d?a.b=b.b:d=null!=b.c;var e=b.a;if(d)Ae(a,b.c);else if(d=!!b.a)if("/"!=e.charAt(0)&&(c.b&&!c.a?e="/"+e:(c=a.a.lastIndexOf("/"),-1!=c&&(e=a.a.substr(0,c+1)+e))),".."==e||"."==e)e="";else if(-1!=e.indexOf("./")||-1!=e.indexOf("/.")){c=_.qa(e,"/");e=e.split("/");for(var f=[],h=0;h<e.length;){var k=e[h++];"."==k?c&&h==e.length&&f.push(""):".."==k?((1<f.length||
1==f.length&&""!=f[0])&&f.pop(),c&&h==e.length&&f.push("")):(f.push(k),c=!0)}e=f.join("/")}d?a.a=e:d=""!==b.g.toString();d?Be(a,Ce(b.g)):d=!!b.l;d&&_.De(a,b.l);return a};Ee=function(a,b){return a?b?(0,window.decodeURI)(a.replace(/%25/g,"%2525")):(0,window.decodeURIComponent)(a):""};Ge=function(a,b,c){return _.q(a)?(a=(0,window.encodeURI)(a).replace(b,Pe),c&&(a=a.replace(/%25([0-9a-fA-F]{2})/g,"%$1")),a):null};Pe=function(a){a=a.charCodeAt(0);return"%"+(a>>4&15).toString(16)+(a&15).toString(16)};
He=/[#\/\?@]/g;Je=/[#\?:]/g;Ie=/[#\?]/g;Me=/[#\?@]/g;Ke=/#/g;Fe=function(a,b,c){this.b=this.a=null;this.g=a||null;this.c=!!c};Qe=function(a){a.a||(a.a=new _.K,a.b=0,a.g&&ce(a.g,function(b,c){a.add((0,window.decodeURIComponent)(b.replace(/\+/g," ")),c)}))};Fe.prototype.add=function(a,b){Qe(this);this.g=null;a=Re(this,a);var c=this.a.get(a);c||this.a.set(a,c=[]);c.push(b);this.b+=1;return this};
Fe.prototype.remove=function(a){Qe(this);a=Re(this,a);return _.jd(this.a,a)?(this.g=null,this.b-=this.a.get(a).length,this.a.remove(a)):!1};Fe.prototype.clear=function(){this.a=this.g=null;this.b=0};var Se=function(a,b){Qe(a);b=Re(a,b);return _.jd(a.a,b)};_.g=Fe.prototype;_.g.forEach=function(a,b){Qe(this);this.a.forEach(function(c,d){(0,_.x)(c,function(c){a.call(b,c,d,this)},this)},this)};
_.g.W=function(){Qe(this);for(var a=this.a.R(),b=this.a.W(),c=[],d=0;d<b.length;d++)for(var e=a[d],f=0;f<e.length;f++)c.push(b[d]);return c};_.g.R=function(a){Qe(this);var b=[];if(_.q(a))Se(this,a)&&(b=_.Ia(b,this.a.get(Re(this,a))));else{a=this.a.R();for(var c=0;c<a.length;c++)b=_.Ia(b,a[c])}return b};_.g.set=function(a,b){Qe(this);this.g=null;a=Re(this,a);Se(this,a)&&(this.b-=this.a.get(a).length);this.a.set(a,[b]);this.b+=1;return this};
_.g.get=function(a,b){a=a?this.R(a):[];return 0<a.length?String(a[0]):b};_.Te=function(a,b,c){a.remove(b);0<c.length&&(a.g=null,a.a.set(Re(a,b),_.Ja(c)),a.b+=c.length)};Fe.prototype.toString=function(){if(this.g)return this.g;if(!this.a)return"";for(var a=[],b=this.a.W(),c=0;c<b.length;c++){var d=b[c],e=(0,window.encodeURIComponent)(String(d));d=this.R(d);for(var f=0;f<d.length;f++){var h=e;""!==d[f]&&(h+="="+(0,window.encodeURIComponent)(String(d[f])));a.push(h)}}return this.g=a.join("&")};
var Ce=function(a){var b=new Fe;b.g=a.g;a.a&&(b.a=new _.K(a.a),b.b=a.b);return b},Re=function(a,b){b=String(b);a.c&&(b=b.toLowerCase());return b},Le=function(a,b){b&&!a.c&&(Qe(a),a.g=null,a.a.forEach(function(a,b){var c=b.toLowerCase();b!=c&&(this.remove(b),_.Te(this,c,a))},a));a.c=b};
var Ue;Ue=function(a){return(a=a.exec(_.Ka))?a[1]:""};_.Xe=function(){if(ub)return Ue(/Firefox\/([0-9.]+)/);if(_.z||db||cb)return pb;if(yb)return Wa()?Ue(/CriOS\/([0-9.]+)/):Ue(/Chrome\/([0-9.]+)/);if(zb&&!Wa())return Ue(/Version\/([0-9.]+)/);if(vb||wb){var a=/Version\/(\S+).*Mobile\/(\S+)/.exec(_.Ka);if(a)return a[1]+"."+a[2]}else if(xb)return(a=Ue(/Android\s+([0-9.]+)/))?a:Ue(/Version\/([0-9.]+)/);return""}();
var Ye=function(a,b){_.ld.call(this,a,b);this.U=b};_.v(Ye,_.ld);var Ze=function(a){_.B(this,a,"capi_md1571",null,null)};_.v(Ze,_.A);var $e={vb:0,Kc:1,Ic:2,ub:3,hb:4};Ze.messageId="capi_md1571";var af=function(a){_.B(this,a,0,null,null)};_.v(af,_.A);var cf=function(){for(var a=10,b=bf,c=b.length,d="";0<a--;)d+=b.charAt(Math.floor(Math.random()*c));return d},bf="abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789";_.df=function(a,b){_.G.call(this);this.j=b||cf();this.c=this.a="";this.b=this.g=null;this.l=a;this.h=new _.O(this);_.J(this,this.h);this.h.listen(window,"message",this.m)};_.v(_.df,_.G);_.df.prototype.ca=function(a,b,c){this.c=a;this.g=b;this.b=c};
_.df.prototype.m=function(a){a=a.a;var b=a.origin;this.g&&this.g!=a.source||"*"!=this.c&&this.c!=b?b=!1:this.b?(b=(new _.Q(b)).b,b=_.ra(b,this.b)?b.length==this.b.length||"."==this.b[0]||"."==b[b.length-1-this.b.length]:!1):b=!0;if(b&&(b=a.data)&&_.q(b)&&"["==b[0]){try{var c=JSON.parse(b);if(!_.t(c))return}catch(d){return}if(0!=c.length&&"capi_md1571"==c[0]&&(c=new Ze(c),_.C(c,1)==this.j)){b=_.C(c,3);if(!this.a)this.a=b;else if(this.a!=b)return;"*"!=this.c&&this.g||this.ca(a.origin,a.source);1==_.C(c,
2)?this.send(2):this.l(c,a)}}};_.df.prototype.send=function(a,b,c){if(this.a&&this.g){b=b||new Ze;_.D(b,3,this.j);_.D(b,1,this.a);_.D(b,2,a);var d=JSON.stringify(_.Gb(b)),e=this.g,f=this.c;_.z?_.$d(function(){e.postMessage(d,f)}):c?e.postMessage(d,f,c):e.postMessage(d,f)}};
var ef=function(a,b,c,d,e){this.g=_.lc();this.a=new _.df((0,_.u)(this.h,this),d);this.a.ca(a,b,e);this.a.a=c;this.b=new _.Zd(50);this.b.start();_.Fd(this.b,"tick",this.c,!1,this);this.c();a=this.g.a;b=this.j;b=jc(b,b,this);b.g=!0;sc(a,b)};ef.prototype.j=function(){_.I(this.a);_.Md(this.b,"tick",this.c,!1,this);_.I(this.b)};ef.prototype.c=function(){this.a.send(1)};ef.prototype.h=function(a,b){2==_.C(a,2)&&this.g.b(b.origin)};
var ff=function(a,b,c){_.G.call(this);this.b=a;a=_.C(b,3);b=_.C(b,1);this.a=new _.df((0,_.u)(this.g,this),b);this.a.a=a;c&&this.a.ca(c.origin,c.source);_.J(this,this.a)};_.v(ff,_.G);ff.prototype.send=function(a){var b=new Ze;_.F(b,4,a);this.a.send($e.vb,b)};ff.prototype.connect=function(a,b){this.a.ca(a,b);this.a.send($e.ub)};ff.prototype.g=function(a){_.C(a,2)==$e.vb&&(a=_.E(a,af,4),this.b(a))};ff.prototype.c=_.fa;
var hf=function(a,b,c){_.G.call(this);this.h=a;this.b=this.a=this.g=null;c?(this.b=c.ports[0],gf(this)):(this.a=new _.df(_.fa,_.C(b,1)),a=_.C(b,3),this.a.a=a)};_.v(hf,_.G);hf.prototype.v=function(){hf.A.v.call(this);this.b&&this.b.close();_.I(this.a)};hf.prototype.c=function(){this.g=new _.O(this);_.J(this,this.g);gf(this)};hf.prototype.send=function(a){this.b.postMessage(_.Gb(a))};
hf.prototype.connect=function(a,b){var c=new window.MessageChannel;this.b=c.port1;gf(this);var d=this.a;this.a=null;c=c.port2;d.ca(a,b);d.send($e.hb,void 0,[c]);_.I(d)};var gf=function(a){a.b&&a.g&&(a.g.listen(a.b,"message",a.j),a.b.start())};hf.prototype.j=function(a){a=a.a;try{var b=new af(a.data)}catch(c){return}this.h(b)};
var jf=function(a,b,c){var d=!1;_.p(_.C(b,2))?_.C(b,2)==$e.hb&&(d=!0):d=yb;return d?new hf(a,b,c):new ff(a,b,c)};var of,qf;_.kf=function(){_.L.call(this);this.j=null;this.l=!1;this.h=[];this.c=[];_.H(this,this.o,this);this.b=null};_.v(_.kf,_.L);_.kf.prototype.o=function(){for(;this.c.length;)this.c.shift()()};_.mf=function(a){a.o();a.h=[];a.b=new _.xc;a.c.push((0,_.u)(a.b.cancel,a.b));a.l=!1;_.Ec(a.b.b(),function(a){(Ad(this.g)||this.J)&&_.lf(this);this.c.push(_.na(_.I,a))},a)};_.kf.prototype.sendMessage=function(a){nf(this,_.Gb(a))};var nf=function(a,b){if(a.b){var c=new af;_.D(c,1,b);_.Ec(a.b.b(),function(a){a.send(c)})}};
_.kf.prototype.I=function(){return this};_.kf.prototype.ca=function(a,b,c){this.a.ca(a,b,c)};_.pf=function(a,b,c,d){_.mf(a);of(a,b,c,d).then(function(a){var d=new Ze;_.D(d,1,a.Fc);_.D(d,3,c);d=jf((0,_.u)(this.m,this),d);d.connect(a.origin,b);this.b.g(d)},void 0,a)};of=function(a,b,c,d){var e=cf();b=(new ef("*",b,c,e,d)).g.a;a.c.push((0,_.u)(b.cancel,b));return b.then(function(a){return{Fc:e,origin:a}})};
_.kf.prototype.C=function(a,b){if(_.C(a,2)==$e.ub||_.C(a,2)==$e.hb)_.I(this.a),this.a=null,this.b.g(jf((0,_.u)(this.m,this),a,b))};_.kf.prototype.m=function(a){this.h.push(a);this.w()};_.kf.prototype.w=function(){for(;qf(this););};qf=function(a){if(a.G||!a.l||0==a.h.length)return!1;var b=_.C(a.h.shift(),1);a.j&&nf(a.j,b);_.M(a,new Ye(b[0],b));return!0};_.lf=function(a){a.l||(a.l=!0,a.b&&_.Ec(a.b.b(),function(a){a.c();_.$d(this.w,0,this)},a))}; _.kf.prototype.listen=function(a,b,c,d){_.lf(this);return _.kf.A.listen.call(this,a,b,c,d)};_.kf.prototype.Sa=function(a,b,c,d){_.lf(this);return _.kf.A.Sa.call(this,a,b,c,d)};_.kf.prototype.H=function(a){_.lf(this);return _.kf.A.H.call(this,a)};
var rf=function(a){this.b=a;this.c="empty";this.a=null;this.g={}};rf.prototype.na=function(a){this.c=a;return this};rf.prototype.Ua=function(a){this.a=a;return this};rf.prototype.tb=function(a){this.g=_.Ra(a);return this};var sf=function(){};var tf=function(){};_.v(tf,sf);tf.prototype.clear=function(){var a=gd(this.ha(!0)),b=this;(0,_.x)(a,function(a){b.remove(a)})};var uf=function(a){this.a=a};_.v(uf,tf);_.g=uf.prototype;_.g.isAvailable=function(){if(!this.a)return!1;try{return this.a.setItem("__sak","1"),this.a.removeItem("__sak"),!0}catch(a){return!1}};_.g.set=function(a,b){try{this.a.setItem(a,b)}catch(c){if(0==this.a.length)throw"Storage mechanism: Storage disabled";throw"Storage mechanism: Quota exceeded";}};_.g.get=function(a){a=this.a.getItem(a);if(!_.q(a)&&null!==a)throw"Storage mechanism: Invalid value was encountered";return a};_.g.remove=function(a){this.a.removeItem(a)};
_.g.ha=function(a){var b=0,c=this.a,d=new dd;d.next=function(){if(b>=c.length)throw cd;var d=c.key(b++);if(a)return d;d=c.getItem(d);if(!_.q(d))throw"Storage mechanism: Invalid value was encountered";return d};return d};_.g.clear=function(){this.a.clear()};_.g.key=function(a){return this.a.key(a)};
var vf=function(){var a=null;try{a=window.localStorage||null}catch(b){}this.a=a};_.v(vf,uf);var xf=function(a,b){this.g=a;this.a=[];this.b=null;b&&(this.b=new vf);if(null!=this.b&&this.b.isAvailable()&&(a=this.b.get("__webmonitoring_RateThrottler_history_hourlyRate"),null!=a))try{this.a=JSON.parse(a)||[]}catch(c){}a=!1;_.t(this.a)||(this.a=[],a=!0);for(;this.a.length>this.g;)this.a.shift(),a=!0;a&&wf(this)},wf=function(a){if(null!=a.b&&a.b.isAvailable())try{a.b.set("__webmonitoring_RateThrottler_history_hourlyRate",_.Zc(a.a))}catch(b){}};
var yf=function(a){_.G.call(this);this.a=a;this.h=!1};_.v(yf,_.G);yf.prototype.setEnabled=function(a){this.h=a};var S=function(a){yf.call(this,a);this.o=100;this.m={};this.O=null;this.g="";this.J=!0;this.j=10;this.b=null;this.c=!1};_.v(S,yf);S.prototype.Ib=function(a){this.J=a;return this};S.prototype.setUseLocalStorage=S.prototype.Ib;S.prototype.Dc=function(a){this.j=Math.min(a,100);return this};S.prototype.setMaxErrorsPerHour=S.prototype.Dc;S.prototype.Gb=function(a){this.o=a;return this};S.prototype.setGlobalSampling=S.prototype.Gb;S.prototype.xb=function(a,b){this.m[a]=b;return this};
S.prototype.addPerErrorMessageSampling=S.prototype.xb;S.prototype.Fb=function(a){this.O=a;return this};S.prototype.setCallback=S.prototype.Fb;S.prototype.Cc=function(a){this.g=a;return this};S.prototype.setClientId=S.prototype.Cc;S.prototype.enable=function(){if(this.h)return!1;this.l=window.onerror;window.onerror=this.w.bind(this);this.setEnabled(!0);return!0};S.prototype.enable=S.prototype.enable;
S.prototype.Cb=function(a,b,c,d,e){var f=_.Ne(window.location.href);a=null!=e&&null!=e.message?e.message:a;var h;if(h=!_.ja(this.O)||this.O(f.a,a,b,c,d,e))if(h=this.c){h=Object.keys(this.m);for(var k=100,n=0;n<h.length;++n){var r=h[n];(new RegExp(r)).test(a)&&(k=this.m[r])}if(h=(100*Math.random()).toFixed(6)>=this.o*k/100?!1:!0){0<=this.j&&null===this.b&&(this.b=new xf(this.j,this.J));if(null===this.b)h=!1;else{a:{h=this.b;k=(0,_.m)();if(h.a.length==h.g)if(h.a[0]<k-36E5)h.a.shift();else{h=!1;break a}h.a.push(k);
wf(h);h=!0}h=!h}h=!h&&this.c}}h&&(h=_.Ra(this.a.g),h.url=f.a,h.type="JavascriptError",h.error_message=a,k="Other",cb?k="Opera":_.z?k="Internet Explorer":ub?k="Firefox":yb?k="Chrome":zb&&(k="Safari"),h.browser=k,h.browser_version=_.Xe,h.os=_.Za()?"Chrome OS":_.y("Linux")?"Linux":_.Ya()?"Windows":_.y("Android")?"Android":Va()?"iPhone":_.y("iPad")?"iPad":_.y("iPod")?"iPod":_.Xa()?"Mac":"Unknown",k=_.Ka,n="",_.Ya()?(n=/Windows (?:NT|Phone) ([0-9.]+)/,n=(k=n.exec(k))?k[1]:"0.0"):Wa()?(n=/(?:iPhone|iPod|iPad|CPU)\s+OS\s+(\S+)/,
n=(k=n.exec(k))&&k[1].replace(/_/g,".")):_.Xa()?(n=/Mac OS X ([0-9_.]+)/,n=(k=n.exec(k))?k[1].replace(/_/g,"."):"10"):_.y("Android")?(n=/Android\s+([^\);]+)(\)|;)/,n=(k=n.exec(k))&&k[1]):_.Za()&&(n=/(?:CrOS\s+(?:i686|x86_64)\s+([0-9.]+))/,n=(k=n.exec(k))&&k[1]),h.os_version=n||"",null!=this.a.a&&(h.channel=this.a.a),_.sa(this.g)||(h.guid=this.g),null!=b&&(h.src=b),null!=c&&(h.line=c),null!=d&&(h.column=d),h.prod=this.a.b,h.ver=this.a.c,c=null!=e?_.wa(e.stack):"",b=zf(h),_.sa(a)||(d=c.split("\n"),
-1<d[0].indexOf(a)&&(d.splice(0,1),c=d.join("\n"))),Af(this,"https://clients2.google.com/cr/staging_report",b,c),f={product:this.a.b,url:f.a,js_errors_count:"1"},a=_.wa(this.a.a),_.sa(a)||(f.version=a),Af(this,"https://clients2.google.com/cr/staging_perf",zf(f)))};S.prototype.reportError=S.prototype.Cb;S.prototype.w=function(a,b,c,d,e){this.Cb(a,b,c,d,e);null!=this.l&&_.ja(this.l)&&this.l(a,b,c,d,e)};
var zf=function(a){var b="",c;for(c in a)b+=_.sa(b)?"?":"&",b+=c+"="+(0,window.encodeURIComponent)(a[c]);return b},Af=function(a,b,c,d){d=d||"";var e=_.sa(d)?{}:{"Content-Type":"text/plain"};_.he(b+c,a.H.bind(a,b),"POST",d,e,6E4,!0)};S.prototype.H=function(a,b){_.qe(b.target)};
var Bf=function(a){yf.call(this,a);this.O=null;this.b=0};_.v(Bf,yf);Bf.prototype.Fb=function(a){this.O=a;return this};var Cf=[{age:6E4,name:"1m"},{age:15E5,name:"25m"},{age:36E5,name:"1h"},{age:36E6,name:"10h"}];Bf.prototype.enable=function(){if(this.h)return!1;if(window.performance&&window.performance.memory){var a=new _.Zd(6E4);_.J(this,a);var b=new _.O(this);_.J(this,b);b.listen(a,"tick",this.g);a.start();this.setEnabled(!0);return!0}return!1};
Bf.prototype.g=function(){this.b+=6E4;for(var a="",b=0;b<Cf.length;++b)if(this.b==Cf[b].age){a=Cf[b].name;break}if(""!=a){b=Df.test(_.Ka)?"":"32_bit_";var c=window.performance.memory;if(c.totalJSHeapSize&&c.usedJSHeapSize){a=[{name:"total_"+b+"js_heap_size_mb_"+a+"_raw",displayName:"Total JS heap (MB)",value:Math.round(c.totalJSHeapSize/1048576)},{name:"used_"+b+"js_heap_size_mb_"+a+"_raw",displayName:"Used JS heap (MB)",value:Math.round(c.usedJSHeapSize/1048576)}];b=_.Ne(window.location.href).a;
c="?product="+(0,window.encodeURIComponent)(this.a.b)+"&url="+(0,window.encodeURIComponent)(b);var d=_.wa(this.a.a);_.sa(d)||(c+="&version="+(0,window.encodeURIComponent)(d));for(d=0;d<a.length;++d)c+="&"+(0,window.encodeURIComponent)(a[d].name)+"="+a[d].value,_.ja(this.O)&&this.O(b,a[d].displayName,a[d].value);_.he("https://clients2.google.com/cr/staging_perf"+c,Ef,"POST","",null,6E4,!0)}}};var Ef=function(a){_.qe(a.target)},Df=/(x86_64|Win64)/;
var Ff=function(a){_.G.call(this);this.b=new rf(a);this.a={}};_.v(Ff,_.G);_.oa("webmonitoring.Monitoring",Ff);Ff.prototype.na=function(a){this.b.na(a);return this};Ff.prototype.setVersion=Ff.prototype.na;Ff.prototype.Ua=function(a){this.b.Ua(a);return this};Ff.prototype.setChannel=Ff.prototype.Ua;Ff.prototype.tb=function(a){this.b.tb(a);return this};Ff.prototype.setContext=Ff.prototype.tb;Ff.prototype.Qa=function(){null!=this.a[2]||(this.a[2]=new S(this.b));return this.a[2]}; Ff.prototype.createJsErrorsReporter=Ff.prototype.Qa;
var Gf=function(a){Ff.call(this,a)};_.v(Gf,Ff);Gf.prototype.Qa=function(){var a=Gf.A.Qa.call(this);a.c=!0;return a};_.Hf=function(){var a=new Gf("Google_Hangouts_Chrome");a.Ua(window.chrome.runtime.id);a.na(window.chrome.runtime.getManifest().version);null!=a.a[1]||(a.a[1]=new Bf(a.b));a.a[1].enable();a.Qa().Ib(!1).Gb(100).xb("Script error.",0).enable()};
}catch(e){_._DumpException(e)}
/* _Module_:host */
try{
var mp=function(a,b){_.mc(a,null,b,void 0)},np=function(a){_.B(this,a,"uv_r_hrd",null,null)};_.v(np,_.A);np.messageId="uv_r_hrd";
var op=function(a,b){return a.g.get(b)},pp=function(a,b){a.j=b;_.H(a,function(){this.j=null},a);_.lf(a)},qp=function(a,b){for(var c=1;c<arguments.length;c++){var d=arguments[c];if(_.ia(d)){var e=a.length||0,f=d.length||0;a.length=e+f;for(var h=0;h<f;h++)a[e+h]=d[h]}else a.push(d)}},rp=function(a){var b=new _.kf;_.mf(b);b.a=new _.df((0,_.u)(b.C,b),a);b.a.ca("*",void 0,void 0);b.c.push(_.na(_.I,b.a));return b};
var sp=function(a){this.a=a;_.z||(delete this.a.lpu,delete this.a.ppu)},tp=["cn","tp"],up=function(a,b){if(_.ja(window.document.postMessage)||_.ja(window.postMessage)||_.z&&window.postMessage)var c=1;else if(_.eb)c=2;else{var d;if(d=_.z){d=!1;try{c=window.opener,window.opener={},d=_.ab(window,"opener"),window.opener=c}catch(e){}}c=d?6:4}d={};d.cn=Math.floor(2147483648*Math.random()).toString(36);d.tp=c;d.ifrid=b;d.pu=a;return new sp(d)};_.oa("GTalk_IFrameChannelConfig.build",up);
var vp=function(){},yp=function(a){var b=a.pa,c=function(a){c.A.constructor.call(this,a);var b=this.Z.length;this.a=[];for(var d=0;d<b;++d)this.Z[d].Zc||(this.a[d]=new this.Z[d](a))};_.v(c,b);for(var d=[];a;){if(b=a.pa){b.Z&&qp(d,b.Z);var e=b.prototype,f;for(f in e)if(e.hasOwnProperty(f)&&_.ja(e[f])&&e[f]!==b){var h=!!e[f].Xb,k=wp(f,e,d,h);(h=xp(f,e,k,h))&&(c.prototype[f]=h)}}a=a.A&&a.A.constructor}c.prototype.Z=d;return c},wp=function(a,b,c,d){for(var e=[],f=0;f<c.length&&(c[f].prototype[a]===b[a]||
(e.push(f),!d));++f);return e},xp=function(a,b,c,d){var e;c.length?d?e=function(b){var d=this.a[c[0]];return d?d[a].apply(this.a[c[0]],arguments):this.Z[c[0]].prototype[a].apply(this,arguments)}:b[a].Zb?e=function(b){a:{var d=Array.prototype.slice.call(arguments,0);for(var e=0;e<c.length;++e){var f=this.a[c[e]];if(f=f?f[a].apply(f,d):this.Z[c[e]].prototype[a].apply(this,d)){d=f;break a}}d=!1}return d}:b[a].Yb?e=function(b){a:{var d=Array.prototype.slice.call(arguments,0);for(var e=0;e<c.length;++e){var f=
this.a[c[e]];f=f?f[a].apply(f,d):this.Z[c[e]].prototype[a].apply(this,d);if(null!=f){d=f;break a}}d=void 0}return d}:b[a].pc?e=function(b){for(var d=Array.prototype.slice.call(arguments,0),e=0;e<c.length;++e){var f=this.a[c[e]];f?f[a].apply(f,d):this.Z[c[e]].prototype[a].apply(this,d)}}:e=function(b){for(var d=Array.prototype.slice.call(arguments,0),e=[],f=0;f<c.length;++f){var r=this.a[c[f]];e.push(r?r[a].apply(r,d):this.Z[c[f]].prototype[a].apply(this,d))}return e}:d||b[a].Zb||b[a].Yb||b[a].pc? e=null:e=zp;return e},zp=function(){return[]};vp.prototype.j=function(a){if(this.a)for(var b=0;b<this.a.length;++b)if(this.a[b]instanceof a)return this.a[b];return null};var Ap=function(a){(a?a:function(){}).Xb=!0};
var Bp=function(){};_.v(Bp,vp);Bp.prototype.b=function(a){return a};Ap(Bp.prototype.b);Bp.prototype.g=function(){return!0};Ap(Bp.prototype.g);var Cp=function(a){_.B(this,a,0,null,null)};_.v(Cp,_.A);var Dp=function(a,b){var c=new Cp;_.D(c,1,b);_.D(c,2,a);return c},Ep=Dp("?",0),Fp=Dp("q",1),Gp=Dp("<",2),Hp=Dp(">",3),Ip=Dp("~",4),Jp=Dp("s",5),Kp={Jc:Ep,Sc:Fp,Mc:Gp,Nc:Hp,Lc:Ip,Uc:Jp};var Lp=function(a){_.B(this,a,"h_cc",null,null)};_.v(Lp,_.A);var Mp=function(a){_.B(this,a,0,null,null)};_.v(Mp,_.A);var Np=function(a){_.B(this,a,0,null,null)};_.v(Np,_.A);var Op=function(a){_.B(this,a,0,null,null)};_.v(Op,_.A);var Pp=function(a){_.B(this,a,0,null,null)};_.v(Pp,_.A);Lp.messageId="h_cc";var Qp=function(a,b){_.D(a,3,b)},Rp=function(a,b){_.D(a,4,b)},Sp=function(a,b){_.D(a,11,b)};
var Tp=function(a){_.B(this,a,"ci:ec",null,null)};_.v(Tp,_.A);Tp.messageId="ci:ec";var Up=function(a){return this.ob.j(a)};var Vp=function(a){this.a=a||{cookie:""}};_.g=Vp.prototype;_.g.set=function(a,b,c,d,e,f){if(/[;=\s]/.test(a))throw Error("D`"+a);if(/[;\r\n]/.test(b))throw Error("E`"+b);_.p(c)||(c=-1);e=e?";domain="+e:"";d=d?";path="+d:"";f=f?";secure":"";c=0>c?"":0==c?";expires="+(new Date(1970,1,1)).toUTCString():";expires="+(new Date((0,_.m)()+1E3*c)).toUTCString();this.a.cookie=a+"="+b+e+d+c+f};
_.g.get=function(a,b){for(var c=a+"=",d=(this.a.cookie||"").split(";"),e=0,f;e<d.length;e++){f=(0,_.ua)(d[e]);if(0==f.lastIndexOf(c,0))return f.substr(c.length);if(f==a)return""}return b};_.g.remove=function(a,b,c){var d=_.p(this.get(a));this.set(a,"",0,b,c);return d};_.g.W=function(){return Wp(this).keys};_.g.R=function(){return Wp(this).values};_.g.clear=function(){for(var a=Wp(this).keys,b=a.length-1;0<=b;b--)this.remove(a[b])}; var Wp=function(a){a=(a.a.cookie||"").split(";");for(var b=[],c=[],d,e,f=0;f<a.length;f++)e=(0,_.ua)(a[f]),d=e.indexOf("="),-1==d?(b.push(""),c.push(e)):(b.push(e.substring(0,d)),c.push(e.substring(d+1)));return{keys:b,values:c}};
var Xp=function(a,b,c){if(!this.ob){for(var d=this.constructor;d&&!d.pa;)d=d.A&&d.A.constructor;d.pa.Ab||(d.pa.Ab=yp(d));this.ob=new d.pa.Ab(this);this.j||(this.j=Up)}var e=this.ob.b(a.clientBaseUrl||"https://talkgadget.google.com/talkgadget/");if(_.qa(e,"https://talkgadget.google.com/talkgadget/")){d=(new Vp(window.document)).get("WCSDBG","");d=d.split(";")[0];d=d.split("|")[0];var f=["plus.google.com"],h=/^[-_a-zA-Z0-9\.]+\.talkgadget\.google\.com$/;0<d.length&&!_.Fa(f,d)&&h.test(d)&&(e=_.Ne(e),
e=_.Ne("https://"+d+e.a).toString())}this.g=e;this.c=c||new Tp;a.notificationsOnly&&_.D(this.c,1,!0);this.b="0";null!=a.authUser?this.b=a.authUser:(c=op(new _.Q(window.location.href),"authuser"),null!=c&&(this.b=c));this.o=a.clientUrl||"notifierclient";c=op(_.Ne(this.o),"authuser");null!=c&&(this.b=c);this.Wa=a.propertyName||"Google Talk";this.H=a.cssUrl;this.locale=a.locale;this.l=a.debug;this.Oa=a.userJid;this.La=a.uiVersion;this.jc=null!=a.rosterExpanded?a.rosterExpanded:!0;this.ba=a.hostLogMinValue;
this.za=a.hideChat;this.ac=a.refresh;this.N=a.hideProfileCard;this.V=a.hideStatusMsgs;this.T=a.hideRosterOptions;this.S=a.hideRecentConversations;this.M=a.hideOTR;this.mb=a.hostServerMessageCallback||!1;this.ga=a.isCentralRoster;this.$b=a.isFullFrame||!1;this.hc=a.rosterClass||"talk_roster";this.kc=a.rosterId||"talk_roster";this.a="gtn-roster-iframe-id";a.rosterFrameId&&a.rosterFrameId.match(/[\w-]/)&&(this.a=a.rosterFrameId);a.rosterIframeIdB&&a.rosterIframeIdB.match(/[\w-]/);this.ya=a.parentToken;
this.gc=b||!1;this.h=_.p(a.isRtl)?a.isRtl:_.Kc.test(this.locale);this.position=a.position||"l";if(!a.keyboardShortcuts){b=[];for(var k in Kp)b.push(_.Gb(Kp[k]))}this.C=a.entityId;this.Ma=a.useQuasarPanels||!1;this.Aa=a.silent||!1;this.nb=a.ignoreCentralRoster||!1;this.cc=a.lazy||!1;this.jb=a.handleProfileLinks||!1;this.Y=a.hostSettings;this.m=a.screen;this.w=a.docsConfig;this.bc=a.jsmode;this.xa=a.moleWidth;this.wa=a.moleHeight;this.va=a.minimizedMoleHeight||36;this.lc=a.derp;this.Ka=window.location.protocol+
"//"+window.location.host;this.D="";this.L=a.optOutAllowed;this.F=a.legacyTalkSignedIn;this.Na=a.useSpareMole;this.J=a.conversationId};Bp.A||_.v(Bp,vp);Xp.pa=Bp;
var Zp=function(a){var b={},c=_.Fb(a,1,"hangouts.google.com"),d="";0>c.indexOf("://")&&(d="https://",0<=c.indexOf(":")&&23!=_.C(a,2)&&27!=_.C(a,2)&&(d="http://"));-1!=c.indexOf("talkgadget.")?(b.clientBaseUrl=d+c+"/talkgadget/_/",b.clientUrl="chat"):(b.clientBaseUrl=d+c+"/webchat/u/"+_.Fb(a,8,"0")+"/",b.clientUrl="load");b.authUser=_.Fb(a,8,"0");b.propertyName=Yp(_.C(a,2));b.locale=_.C(a,4);b.hideProfileCard=!0;b.parentToken=_.C(a,3);b.isRtl=_.Fb(a,6,!1);b.lazy=_.Fb(a,7,!1);b.entityId=_.C(a,9);b.hostSettings=
_.C(a,5);b.jsmode=_.C(a,11);b.isFullFrame=_.Fb(a,13,!1);b.rosterId=_.Fb(a,12,"talk_roster");b.rosterIframeIdB=_.Fb(a,15,"gtn-roster-iframe-id-b");b.derp=!!_.Fb(a,16,!1);c=_.E(a,Pp,14);null!=c&&(b.isCentralRoster=_.Fb(c,1,!1),b.useQuasarPanels=_.Fb(c,2,!1));c=_.E(a,Mp,10);null!=c&&(b.moleManagerLeftMargin=_.C(c,1),b.moleManagerMiddleMargin=_.C(c,2),b.moleManagerRightMargin=_.C(c,3),b.moleManagerNoMoleAreaMargin=_.C(c,4),b.moleManagerBoundingElementId=_.C(c,5),b.moleWidth=_.C(c,6),b.moleHeight=_.C(c,
7),b.minimizedMoleHeight=_.C(c,8));c=_.E(a,Np,18);null!=c&&(b.optOutAllowed=_.Fb(c,1,!0),d=_.E(c,Op,3),null!=d&&(b.legacyTalkSignedIn=_.Fb(d,1,!0)),c=_.C(c,4),null!=c&&(b.useSpareMole=c));b.uiVersion=2;b.hideStatusMsgs=!0;b.hideRecentConversations=!0;c=new Tp;_.D(c,2,!0);_.D(c,1,!0);_.D(c,3,!1);b.endpointConfig=c;b.ignoreAutomatedRoster=_.Fb(a,17,!1);b.conversationId=_.C(a,19);return b},Yp=function(a){switch(a){case 1:return"homepage";case 4:return"Google Translator Toolkit";case 5:return"Google Sites";
case 6:return"customersupport";case 9:return"present";case 15:return"hangout";case 18:return"gmail";case 20:return"docs";case 24:return"docs_hangout";case 22:return"hangout_lite";case 23:return"aChromeExtension";case 25:return"bigtop";case 27:return"ChromeApp";case 36:return"StartPage"}},$p=function(a,b){if(-1!=a.indexOf("talkgadget.")){var c=_.Ne(a),d=c.a;if(0<=d.indexOf("/u/"))return a;a=d.lastIndexOf("_/");if(0>a||a!=d.length-2)d+="_/";c.a="/u/"+b+d;return c.toString()}return a};
var aq=function(a,b,c,d,e){_.G.call(this);this.a=a;this.b=d||window.document;this.g=new _.O(this);_.J(this,this.g);var f=_.Ka;d=new _.Q(a.g+a.o);_.Fb(a.c,2,!1)||(_.R(d,"ts","0"),_.R(d,"re",a.jc),_.R(d,"ref",a.ac));_.R(d,"client","sm");_.R(d,"prop",a.Wa);_.R(d,"nav","true");_.R(d,"fid",a.a);a.l&&_.R(d,"debug",a.l);_.R(d,"os",_.gb);_.R(d,"stime",c);a.za&&_.R(d,"hc",a.za);for(c=0;c<tp.length;++c);b=_.Zc(b.a);_.R(d,"xpc",b);_.R(d,"ec",_.Zc(_.Gb(a.c)));a.m&&_.R(d,"screen",a.m);-1!=f.indexOf("MSIE")&&_.R(d,
"ua",f);a.ya&&_.R(d,"pvt",a.ya);a.mb&&_.R(d,"hsmc","true");_.p(a.ba)&&_.R(d,"logl",a.ba);b=window.location.href;0>b.indexOf("?rel=1")&&(b=b.split("?"),b[1]=1==b.length?"rel=1":["rel=1&",b[1]].join(""),_.R(d,"href",b.join("?")));b=new _.Q(window.location.href);"false"==op(b,"uacheck")&&_.R(d,"uacheck",!1);(f=a.bc)&&_.R(d,"jsmode",f);(f=op(b,"cssmode"))&&_.R(d,"cssmode",f);(f=op(b,"convid"))&&_.R(d,"convid",f);if(f=b.g.R("convp"))_.t(f)||(f=[String(f)]),_.Te(d.g,"convp",f);(f=op(b,"smexp"))&&_.R(d,
"smexp",f);f=b.g.R("mods");a.cc&&f.push("lazy");e&&(f=_.Ia(f,e));0<f.length&&_.R(d,"mods",f.join(","));if(!a.g||0>a.g.indexOf("/u/"))(e=op(b,"authuser"))?_.R(d,"authuser",e):null!=a.b&&_.R(d,"authuser",a.b);e=op(b,"eid");_.sa(_.wa(e))||_.R(d,"eid",e);_.sa(_.wa(this.a.C))||_.R(d,"eid",this.a.C);null!=this.a.position&&_.R(d,"pos",this.a.position);_.p(a.La)&&_.R(d,"uiv",this.a.La);a.H&&_.R(d,"css",a.H);e=a.locale||op(b,"hl");null!=e&&_.R(d,"hl",e);_.p(a.Oa)&&_.R(d,"uj",a.Oa);null!=a.N&&_.R(d,"hpc",a.N);
null!=a.V&&_.R(d,"hsm",a.V);null!=a.T&&_.R(d,"hro",a.T);null!=a.S&&_.R(d,"hrc",a.S);null!=a.M&&_.R(d,"hotr",a.M);null!=a.ga&&_.R(d,"pop",a.ga);a.gc&&_.R(d,"pal","1");null!=a.Ma&&_.R(d,"uqp",a.Ma);null!=a.L&&_.R(d,"gooa",a.L);null!=a.F&&_.R(d,"gltsi",a.F);null!=a.Na&&_.R(d,"gusm",a.Na);null!=a.Aa&&_.R(d,"sl",a.Aa);a.nb&&_.R(d,"icr","1");a.jb&&_.R(d,"hpl","1");a.Y&&_.R(d,"hs",a.Y);a.w&&_.R(d,"dc",_.Zc(_.Gb(a.w)));null!=a.xa&&_.R(d,"molew",a.xa);null!=a.wa&&_.R(d,"moleh",a.wa);null!=a.va&&_.R(d,"mmoleh",
a.va);a.lc&&_.R(d,"derp","1");a.D&&_.R(d,"fcho",a.D);null!=a.Ka&&_.R(d,"two",a.Ka);null!=a.J&&_.R(d,"convid",a.J);_.R(d,"host","1");_.R(d,"zx",Math.floor(2147483648*Math.random()).toString(36)+Math.abs(Math.floor(2147483648*Math.random())^(0,_.m)()).toString(36));this.c=d.toString()};_.v(aq,_.G);aq.prototype.install=function(a,b){bq(this,a,b,_.fa)};
var bq=function(a,b,c,d){var e=a.b.getElementById(b);e||(e=a.b.createElement("div"),e.id=b,e.className=a.a.hc,a.b.body.appendChild(e));a=(0,_.u)(function(){var a="";this.a.$b||(a="height:400px");var b=this.b.createElement("iframe");_.Vc(b,{id:this.a.a,name:this.a.a,"class":"talk_iframe",frameborder:"0",style:a,"aria-hidden":"true"});_.Tc("talk_loading_msg",e)||_.Wc(e);e.appendChild(b);var k=this.b.getElementById(this.a.a);_.te(this.g,k,["load","error"],function(a){k.contentWindow.postMessage("AllowFrame: Chat", "*");d(a)});k.src=this.c.toString();c()},a);window.setTimeout(a,0)};
var cq=function(a){var b=_.Oe(_.C(a,2),"/webchat/extension-start");_.C(a,5)&&_.R(b,"e",_.C(a,5));return new _.gc(function(a,d){_.he(b,function(b){_.qe(b.target)||d();try{var c=b.target;try{var e=c.a?c.a.responseText:""}catch(n){e=""}var k=JSON.parse(e);a(new _.ye(k))}catch(n){d(n.message)}})})};
var eq=function(){var a=this;_.O.call(this);_.P("Starting ...");this.listen(window,"unload",this.$);this.b=new _.ue(JSON.parse((0,window.decodeURI)(window.location.hash.substr(1))));this.a=rp(_.C(this.b,1));_.J(this,this.a);this.g=new _.kf;_.J(this,this.g);mp(cq(this.b).then(function(b){return dq(a,b)}),function(a){_.P("Failed to start : %s.",a||"")})},fq;_.v(eq,_.O);
var dq=function(a,b){if(!a.G&&(a.a.sendMessage(b),_.C(b,1))){var c=new Lp,d=_.Ne(_.C(a.b,2)),e=d.b;null!=d.c&&(e+=":"+d.c);_.D(c,1,e);_.D(c,2,27);_.D(c,13,!0);_.D(c,17,!0);Qp(c,_.C(b,1));Sp(c,_.C(a.b,4));Rp(c,_.C(a.b,3)||"en");b=Zp(c);var f=new Xp(b,!0,b.endpointConfig);f.g=$p(f.g,f.b);f.D=window.location.origin;b=up(f.g,f.a);b=new aq(f,b,(0,_.m)(),window.document);_.J(a,b);bq(b,f.kc,function(){},function(){_.pf(a.g,window.document.getElementById(f.a).contentWindow,"31ACFC0_","google.com");pp(a.g, a.a);pp(a.a,a.g);a.a.sendMessage(new np)})}};_.oa("default_host._DumpException",function(a){return window.console.error(a.stack)});_.Hf();if(!fq||fq.G)fq=new eq;

}catch(e){_._DumpException(e)}
/* _GlobalSuffix_ */
}).call(this,this.default_host);
// Google Inc.
